//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.USRE.USER_DENGLU {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.USRE.USER_DENGLU.USER_DENGLU")]
    public interface USER_DENGLU {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USER_DENGLU/Selectyonghu", ReplyAction="http://tempuri.org/USER_DENGLU/SelectyonghuResponse")]
        System.Data.DataSet Selectyonghu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USER_DENGLU/Selectyonghu", ReplyAction="http://tempuri.org/USER_DENGLU/SelectyonghuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectyonghuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USER_DENGLU/SelectMiMaBYyonghu", ReplyAction="http://tempuri.org/USER_DENGLU/SelectMiMaBYyonghuResponse")]
        System.Data.DataSet SelectMiMaBYyonghu(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USER_DENGLU/SelectMiMaBYyonghu", ReplyAction="http://tempuri.org/USER_DENGLU/SelectMiMaBYyonghuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectMiMaBYyonghuAsync(int UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface USER_DENGLUChannel : 集团客运综合管理系统.BLL集团客运综合管理.USRE.USER_DENGLU.USER_DENGLU, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class USER_DENGLUClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.USRE.USER_DENGLU.USER_DENGLU>, 集团客运综合管理系统.BLL集团客运综合管理.USRE.USER_DENGLU.USER_DENGLU {
        
        public USER_DENGLUClient() {
        }
        
        public USER_DENGLUClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public USER_DENGLUClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USER_DENGLUClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USER_DENGLUClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Selectyonghu() {
            return base.Channel.Selectyonghu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectyonghuAsync() {
            return base.Channel.SelectyonghuAsync();
        }
        
        public System.Data.DataSet SelectMiMaBYyonghu(int UserID) {
            return base.Channel.SelectMiMaBYyonghu(UserID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectMiMaBYyonghuAsync(int UserID) {
            return base.Channel.SelectMiMaBYyonghuAsync(UserID);
        }
    }
}
