//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate")]
    public interface NEWFrequencyUpdate {
        
        // CODEGEN: 参数“FrequencyMC”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/FrequencyUPDATE", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/FrequencyUPDATEResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATEResponse FrequencyUPDATE(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/FrequencyUPDATE", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/FrequencyUPDATEResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATEResponse> FrequencyUPDATEAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATERequest request);
        
        // CODEGEN: 参数“SelectFrequencyResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/SelectFrequency", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/SelectFrequencyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyResponse SelectFrequency(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/SelectFrequency", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/SelectFrequencyResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyResponse> SelectFrequencyAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyRequest request);
        
        // CODEGEN: 参数“SelectFrequencyTIAOResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/SelectFrequencyTIAO", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/SelectFrequencyTIAOResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAOResponse SelectFrequencyTIAO(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/SelectFrequencyTIAO", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/SelectFrequencyTIAOResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAOResponse> SelectFrequencyTIAOAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAORequest request);
        
        // CODEGEN: 参数“LineSelectResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/LineSelect", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/LineSelectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectResponse LineSelect(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/LineSelect", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/LineSelectResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectResponse> LineSelectAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectRequest request);
        
        // CODEGEN: 参数“TicketEntranceSelectResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/TicketEntranceSelect", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/TicketEntranceSelectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectResponse TicketEntranceSelect(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/TicketEntranceSelect", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/TicketEntranceSelectResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectResponse> TicketEntranceSelectAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectRequest request);
        
        // CODEGEN: 参数“VehicleSelectResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/VehicleSelect", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/VehicleSelectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectResponse VehicleSelect(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/VehicleSelect", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/VehicleSelectResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectResponse> VehicleSelectAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectRequest request);
        
        // CODEGEN: 参数“StationSelect1Result”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/StationSelect1", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/StationSelect1Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Response StationSelect1(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/StationSelect1", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/StationSelect1Response")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Response> StationSelect1Async(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Request request);
        
        // CODEGEN: 参数“StationSelectTIAOResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/StationSelectTIAO", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/StationSelectTIAOResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAOResponse StationSelectTIAO(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NEWFrequencyUpdate/StationSelectTIAO", ReplyAction="http://tempuri.org/NEWFrequencyUpdate/StationSelectTIAOResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAOResponse> StationSelectTIAOAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAORequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FrequencyUPDATE", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FrequencyUPDATERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int VehicleID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int LineID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StartingStationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int TerminalStationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int TicketEntranceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int CreateUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int DeleteUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FrequencyMC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DepartureTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CirculationDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public int BeginningDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public int ClassNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public int StopClassDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public bool Generate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public bool WhetherToPas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public System.DateTime CreateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public int FrequencyID;
        
        public FrequencyUPDATERequest() {
        }
        
        public FrequencyUPDATERequest(
                    int VehicleID, 
                    int LineID, 
                    int StartingStationID, 
                    int TerminalStationID, 
                    int TicketEntranceID, 
                    int CreateUserID, 
                    int DeleteUserID, 
                    string FrequencyMC, 
                    string DepartureTime, 
                    string CirculationDate, 
                    int BeginningDays, 
                    int ClassNumber, 
                    int StopClassDays, 
                    bool Generate, 
                    bool WhetherToPas, 
                    string Comments, 
                    System.DateTime CreateTime, 
                    int FrequencyID) {
            this.VehicleID = VehicleID;
            this.LineID = LineID;
            this.StartingStationID = StartingStationID;
            this.TerminalStationID = TerminalStationID;
            this.TicketEntranceID = TicketEntranceID;
            this.CreateUserID = CreateUserID;
            this.DeleteUserID = DeleteUserID;
            this.FrequencyMC = FrequencyMC;
            this.DepartureTime = DepartureTime;
            this.CirculationDate = CirculationDate;
            this.BeginningDays = BeginningDays;
            this.ClassNumber = ClassNumber;
            this.StopClassDays = StopClassDays;
            this.Generate = Generate;
            this.WhetherToPas = WhetherToPas;
            this.Comments = Comments;
            this.CreateTime = CreateTime;
            this.FrequencyID = FrequencyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FrequencyUPDATEResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FrequencyUPDATEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int FrequencyUPDATEResult;
        
        public FrequencyUPDATEResponse() {
        }
        
        public FrequencyUPDATEResponse(int FrequencyUPDATEResult) {
            this.FrequencyUPDATEResult = FrequencyUPDATEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectFrequency", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectFrequencyRequest {
        
        public SelectFrequencyRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectFrequencyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectFrequencyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectFrequencyResult;
        
        public SelectFrequencyResponse() {
        }
        
        public SelectFrequencyResponse(System.Data.DataSet SelectFrequencyResult) {
            this.SelectFrequencyResult = SelectFrequencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectFrequencyTIAO", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectFrequencyTIAORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int FrequencyID;
        
        public SelectFrequencyTIAORequest() {
        }
        
        public SelectFrequencyTIAORequest(int FrequencyID) {
            this.FrequencyID = FrequencyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectFrequencyTIAOResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectFrequencyTIAOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectFrequencyTIAOResult;
        
        public SelectFrequencyTIAOResponse() {
        }
        
        public SelectFrequencyTIAOResponse(System.Data.DataSet SelectFrequencyTIAOResult) {
            this.SelectFrequencyTIAOResult = SelectFrequencyTIAOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LineSelect", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LineSelectRequest {
        
        public LineSelectRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LineSelectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LineSelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet LineSelectResult;
        
        public LineSelectResponse() {
        }
        
        public LineSelectResponse(System.Data.DataSet LineSelectResult) {
            this.LineSelectResult = LineSelectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TicketEntranceSelect", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TicketEntranceSelectRequest {
        
        public TicketEntranceSelectRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TicketEntranceSelectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TicketEntranceSelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet TicketEntranceSelectResult;
        
        public TicketEntranceSelectResponse() {
        }
        
        public TicketEntranceSelectResponse(System.Data.DataSet TicketEntranceSelectResult) {
            this.TicketEntranceSelectResult = TicketEntranceSelectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VehicleSelect", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VehicleSelectRequest {
        
        public VehicleSelectRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VehicleSelectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VehicleSelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet VehicleSelectResult;
        
        public VehicleSelectResponse() {
        }
        
        public VehicleSelectResponse(System.Data.DataSet VehicleSelectResult) {
            this.VehicleSelectResult = VehicleSelectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StationSelect1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StationSelect1Request {
        
        public StationSelect1Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StationSelect1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StationSelect1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet StationSelect1Result;
        
        public StationSelect1Response() {
        }
        
        public StationSelect1Response(System.Data.DataSet StationSelect1Result) {
            this.StationSelect1Result = StationSelect1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StationSelectTIAO", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StationSelectTIAORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StationMC;
        
        public StationSelectTIAORequest() {
        }
        
        public StationSelectTIAORequest(string StationMC) {
            this.StationMC = StationMC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StationSelectTIAOResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StationSelectTIAOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet StationSelectTIAOResult;
        
        public StationSelectTIAOResponse() {
        }
        
        public StationSelectTIAOResponse(System.Data.DataSet StationSelectTIAOResult) {
            this.StationSelectTIAOResult = StationSelectTIAOResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NEWFrequencyUpdateChannel : 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NEWFrequencyUpdateClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate>, 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate {
        
        public NEWFrequencyUpdateClient() {
        }
        
        public NEWFrequencyUpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NEWFrequencyUpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NEWFrequencyUpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NEWFrequencyUpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATEResponse 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.FrequencyUPDATE(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATERequest request) {
            return base.Channel.FrequencyUPDATE(request);
        }
        
        public int FrequencyUPDATE(
                    int VehicleID, 
                    int LineID, 
                    int StartingStationID, 
                    int TerminalStationID, 
                    int TicketEntranceID, 
                    int CreateUserID, 
                    int DeleteUserID, 
                    string FrequencyMC, 
                    string DepartureTime, 
                    string CirculationDate, 
                    int BeginningDays, 
                    int ClassNumber, 
                    int StopClassDays, 
                    bool Generate, 
                    bool WhetherToPas, 
                    string Comments, 
                    System.DateTime CreateTime, 
                    int FrequencyID) {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATERequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATERequest();
            inValue.VehicleID = VehicleID;
            inValue.LineID = LineID;
            inValue.StartingStationID = StartingStationID;
            inValue.TerminalStationID = TerminalStationID;
            inValue.TicketEntranceID = TicketEntranceID;
            inValue.CreateUserID = CreateUserID;
            inValue.DeleteUserID = DeleteUserID;
            inValue.FrequencyMC = FrequencyMC;
            inValue.DepartureTime = DepartureTime;
            inValue.CirculationDate = CirculationDate;
            inValue.BeginningDays = BeginningDays;
            inValue.ClassNumber = ClassNumber;
            inValue.StopClassDays = StopClassDays;
            inValue.Generate = Generate;
            inValue.WhetherToPas = WhetherToPas;
            inValue.Comments = Comments;
            inValue.CreateTime = CreateTime;
            inValue.FrequencyID = FrequencyID;
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATEResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).FrequencyUPDATE(inValue);
            return retVal.FrequencyUPDATEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATEResponse> 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.FrequencyUPDATEAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATERequest request) {
            return base.Channel.FrequencyUPDATEAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATEResponse> FrequencyUPDATEAsync(
                    int VehicleID, 
                    int LineID, 
                    int StartingStationID, 
                    int TerminalStationID, 
                    int TicketEntranceID, 
                    int CreateUserID, 
                    int DeleteUserID, 
                    string FrequencyMC, 
                    string DepartureTime, 
                    string CirculationDate, 
                    int BeginningDays, 
                    int ClassNumber, 
                    int StopClassDays, 
                    bool Generate, 
                    bool WhetherToPas, 
                    string Comments, 
                    System.DateTime CreateTime, 
                    int FrequencyID) {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATERequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.FrequencyUPDATERequest();
            inValue.VehicleID = VehicleID;
            inValue.LineID = LineID;
            inValue.StartingStationID = StartingStationID;
            inValue.TerminalStationID = TerminalStationID;
            inValue.TicketEntranceID = TicketEntranceID;
            inValue.CreateUserID = CreateUserID;
            inValue.DeleteUserID = DeleteUserID;
            inValue.FrequencyMC = FrequencyMC;
            inValue.DepartureTime = DepartureTime;
            inValue.CirculationDate = CirculationDate;
            inValue.BeginningDays = BeginningDays;
            inValue.ClassNumber = ClassNumber;
            inValue.StopClassDays = StopClassDays;
            inValue.Generate = Generate;
            inValue.WhetherToPas = WhetherToPas;
            inValue.Comments = Comments;
            inValue.CreateTime = CreateTime;
            inValue.FrequencyID = FrequencyID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).FrequencyUPDATEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyResponse 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.SelectFrequency(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyRequest request) {
            return base.Channel.SelectFrequency(request);
        }
        
        public System.Data.DataSet SelectFrequency() {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyRequest();
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).SelectFrequency(inValue);
            return retVal.SelectFrequencyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyResponse> 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.SelectFrequencyAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyRequest request) {
            return base.Channel.SelectFrequencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyResponse> SelectFrequencyAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).SelectFrequencyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAOResponse 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.SelectFrequencyTIAO(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAORequest request) {
            return base.Channel.SelectFrequencyTIAO(request);
        }
        
        public System.Data.DataSet SelectFrequencyTIAO(int FrequencyID) {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAORequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAORequest();
            inValue.FrequencyID = FrequencyID;
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAOResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).SelectFrequencyTIAO(inValue);
            return retVal.SelectFrequencyTIAOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAOResponse> 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.SelectFrequencyTIAOAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAORequest request) {
            return base.Channel.SelectFrequencyTIAOAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAOResponse> SelectFrequencyTIAOAsync(int FrequencyID) {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAORequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.SelectFrequencyTIAORequest();
            inValue.FrequencyID = FrequencyID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).SelectFrequencyTIAOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectResponse 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.LineSelect(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectRequest request) {
            return base.Channel.LineSelect(request);
        }
        
        public System.Data.DataSet LineSelect() {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectRequest();
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).LineSelect(inValue);
            return retVal.LineSelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectResponse> 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.LineSelectAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectRequest request) {
            return base.Channel.LineSelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectResponse> LineSelectAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.LineSelectRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).LineSelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectResponse 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.TicketEntranceSelect(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectRequest request) {
            return base.Channel.TicketEntranceSelect(request);
        }
        
        public System.Data.DataSet TicketEntranceSelect() {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectRequest();
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).TicketEntranceSelect(inValue);
            return retVal.TicketEntranceSelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectResponse> 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.TicketEntranceSelectAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectRequest request) {
            return base.Channel.TicketEntranceSelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectResponse> TicketEntranceSelectAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.TicketEntranceSelectRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).TicketEntranceSelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectResponse 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.VehicleSelect(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectRequest request) {
            return base.Channel.VehicleSelect(request);
        }
        
        public System.Data.DataSet VehicleSelect() {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectRequest();
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).VehicleSelect(inValue);
            return retVal.VehicleSelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectResponse> 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.VehicleSelectAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectRequest request) {
            return base.Channel.VehicleSelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectResponse> VehicleSelectAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.VehicleSelectRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).VehicleSelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Response 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.StationSelect1(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Request request) {
            return base.Channel.StationSelect1(request);
        }
        
        public System.Data.DataSet StationSelect1() {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Request inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Request();
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Response retVal = ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).StationSelect1(inValue);
            return retVal.StationSelect1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Response> 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.StationSelect1Async(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Request request) {
            return base.Channel.StationSelect1Async(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Response> StationSelect1Async() {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Request inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelect1Request();
            return ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).StationSelect1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAOResponse 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.StationSelectTIAO(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAORequest request) {
            return base.Channel.StationSelectTIAO(request);
        }
        
        public System.Data.DataSet StationSelectTIAO(string StationMC) {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAORequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAORequest();
            inValue.StationMC = StationMC;
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAOResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).StationSelectTIAO(inValue);
            return retVal.StationSelectTIAOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAOResponse> 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate.StationSelectTIAOAsync(集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAORequest request) {
            return base.Channel.StationSelectTIAOAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAOResponse> StationSelectTIAOAsync(string StationMC) {
            集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAORequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.StationSelectTIAORequest();
            inValue.StationMC = StationMC;
            return ((集团客运综合管理系统.BLL集团客运综合管理.FrequencyManager.NEWFrequencyUpdate.NEWFrequencyUpdate)(this)).StationSelectTIAOAsync(inValue);
        }
    }
}
