//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.Rrepoter.RepoterCheLIng {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.Rrepoter.RepoterCheLIng.RepoterCheLIng")]
    public interface RepoterCheLIng {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RepoterCheLIng/SeleceDaYingBaoBiao", ReplyAction="http://tempuri.org/RepoterCheLIng/SeleceDaYingBaoBiaoResponse")]
        System.Data.DataSet SeleceDaYingBaoBiao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RepoterCheLIng/SeleceDaYingBaoBiao", ReplyAction="http://tempuri.org/RepoterCheLIng/SeleceDaYingBaoBiaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SeleceDaYingBaoBiaoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RepoterCheLIngChannel : 集团客运综合管理系统.BLL集团客运综合管理.Rrepoter.RepoterCheLIng.RepoterCheLIng, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepoterCheLIngClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.Rrepoter.RepoterCheLIng.RepoterCheLIng>, 集团客运综合管理系统.BLL集团客运综合管理.Rrepoter.RepoterCheLIng.RepoterCheLIng {
        
        public RepoterCheLIngClient() {
        }
        
        public RepoterCheLIngClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepoterCheLIngClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepoterCheLIngClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepoterCheLIngClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SeleceDaYingBaoBiao() {
            return base.Channel.SeleceDaYingBaoBiao();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SeleceDaYingBaoBiaoAsync() {
            return base.Channel.SeleceDaYingBaoBiaoAsync();
        }
    }
}
