//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuRuKu {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuRuKu.FRM_PiaoJuRuKu")]
    public interface FRM_PiaoJuRuKu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuRuKu/SelectPiaoJuXinXi", ReplyAction="http://tempuri.org/FRM_PiaoJuRuKu/SelectPiaoJuXinXiResponse")]
        System.Data.DataSet SelectPiaoJuXinXi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuRuKu/SelectPiaoJuXinXi", ReplyAction="http://tempuri.org/FRM_PiaoJuRuKu/SelectPiaoJuXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectPiaoJuXinXiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuRuKu/DeleteBiIIEnterlibraryXinXi", ReplyAction="http://tempuri.org/FRM_PiaoJuRuKu/DeleteBiIIEnterlibraryXinXiResponse")]
        int DeleteBiIIEnterlibraryXinXi(int BiIIEnterlibraryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuRuKu/DeleteBiIIEnterlibraryXinXi", ReplyAction="http://tempuri.org/FRM_PiaoJuRuKu/DeleteBiIIEnterlibraryXinXiResponse")]
        System.Threading.Tasks.Task<int> DeleteBiIIEnterlibraryXinXiAsync(int BiIIEnterlibraryID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_PiaoJuRuKuChannel : 集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuRuKu.FRM_PiaoJuRuKu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_PiaoJuRuKuClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuRuKu.FRM_PiaoJuRuKu>, 集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuRuKu.FRM_PiaoJuRuKu {
        
        public FRM_PiaoJuRuKuClient() {
        }
        
        public FRM_PiaoJuRuKuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_PiaoJuRuKuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PiaoJuRuKuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PiaoJuRuKuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SelectPiaoJuXinXi() {
            return base.Channel.SelectPiaoJuXinXi();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectPiaoJuXinXiAsync() {
            return base.Channel.SelectPiaoJuXinXiAsync();
        }
        
        public int DeleteBiIIEnterlibraryXinXi(int BiIIEnterlibraryID) {
            return base.Channel.DeleteBiIIEnterlibraryXinXi(BiIIEnterlibraryID);
        }
        
        public System.Threading.Tasks.Task<int> DeleteBiIIEnterlibraryXinXiAsync(int BiIIEnterlibraryID) {
            return base.Channel.DeleteBiIIEnterlibraryXinXiAsync(BiIIEnterlibraryID);
        }
    }
}
