//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuRuKu_Insert {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuRuKu_Insert.FRM_PiaoJuRuKu_Insert")]
    public interface FRM_PiaoJuRuKu_Insert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuRuKu_Insert/SelectBiIIType", ReplyAction="http://tempuri.org/FRM_PiaoJuRuKu_Insert/SelectBiIITypeResponse")]
        System.Data.DataSet SelectBiIIType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuRuKu_Insert/SelectBiIIType", ReplyAction="http://tempuri.org/FRM_PiaoJuRuKu_Insert/SelectBiIITypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectBiIITypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuRuKu_Insert/InsertBiIIEnterlibraryXinXi", ReplyAction="http://tempuri.org/FRM_PiaoJuRuKu_Insert/InsertBiIIEnterlibraryXinXiResponse")]
        int InsertBiIIEnterlibraryXinXi(int BiIITypeID, int CreateUserID, int DeleteUserID, int BeginTicketMark, int FinishTicketMark, int CurrentTicketMark, int EnterlibraryQuantity, int Inventory, System.DateTime EnterlibraryDate, string Comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuRuKu_Insert/InsertBiIIEnterlibraryXinXi", ReplyAction="http://tempuri.org/FRM_PiaoJuRuKu_Insert/InsertBiIIEnterlibraryXinXiResponse")]
        System.Threading.Tasks.Task<int> InsertBiIIEnterlibraryXinXiAsync(int BiIITypeID, int CreateUserID, int DeleteUserID, int BeginTicketMark, int FinishTicketMark, int CurrentTicketMark, int EnterlibraryQuantity, int Inventory, System.DateTime EnterlibraryDate, string Comment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_PiaoJuRuKu_InsertChannel : 集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuRuKu_Insert.FRM_PiaoJuRuKu_Insert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_PiaoJuRuKu_InsertClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuRuKu_Insert.FRM_PiaoJuRuKu_Insert>, 集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuRuKu_Insert.FRM_PiaoJuRuKu_Insert {
        
        public FRM_PiaoJuRuKu_InsertClient() {
        }
        
        public FRM_PiaoJuRuKu_InsertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_PiaoJuRuKu_InsertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PiaoJuRuKu_InsertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PiaoJuRuKu_InsertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SelectBiIIType() {
            return base.Channel.SelectBiIIType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectBiIITypeAsync() {
            return base.Channel.SelectBiIITypeAsync();
        }
        
        public int InsertBiIIEnterlibraryXinXi(int BiIITypeID, int CreateUserID, int DeleteUserID, int BeginTicketMark, int FinishTicketMark, int CurrentTicketMark, int EnterlibraryQuantity, int Inventory, System.DateTime EnterlibraryDate, string Comment) {
            return base.Channel.InsertBiIIEnterlibraryXinXi(BiIITypeID, CreateUserID, DeleteUserID, BeginTicketMark, FinishTicketMark, CurrentTicketMark, EnterlibraryQuantity, Inventory, EnterlibraryDate, Comment);
        }
        
        public System.Threading.Tasks.Task<int> InsertBiIIEnterlibraryXinXiAsync(int BiIITypeID, int CreateUserID, int DeleteUserID, int BeginTicketMark, int FinishTicketMark, int CurrentTicketMark, int EnterlibraryQuantity, int Inventory, System.DateTime EnterlibraryDate, string Comment) {
            return base.Channel.InsertBiIIEnterlibraryXinXiAsync(BiIITypeID, CreateUserID, DeleteUserID, BeginTicketMark, FinishTicketMark, CurrentTicketMark, EnterlibraryQuantity, Inventory, EnterlibraryDate, Comment);
        }
    }
}
