//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.InspectTicketManager.FRM_JianPiaoXiTong {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.InspectTicketManager.FRM_JianPiaoXiTong.FRM_JianPiaoXiTong")]
    public interface FRM_JianPiaoXiTong {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangBianHao", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangBianHaoResponse")]
        System.Data.DataSet SelectCheLiangBianHao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangBianHao", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangBianHaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangBianHaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangByCheLiangBianHao", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangByCheLiangBianHaoResponse")]
        System.Data.DataSet SelectCheLiangByCheLiangBianHao(string VehicleNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangByCheLiangBianHao", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangByCheLiangBianHaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangByCheLiangBianHaoAsync(string VehicleNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangXiWeiZhangTai", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangXiWeiZhangTaiResponse")]
        System.Data.DataSet SelectCheLiangXiWeiZhangTai(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangXiWeiZhangTai", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectCheLiangXiWeiZhangTaiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangXiWeiZhangTaiAsync(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectDaiJianCheLiang", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectDaiJianCheLiangResponse")]
        System.Data.DataSet SelectDaiJianCheLiang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectDaiJianCheLiang", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectDaiJianCheLiangResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectDaiJianCheLiangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectJianPiaoXinXi", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectJianPiaoXinXiResponse")]
        System.Data.DataSet SelectJianPiaoXinXi(string TicketMark, int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectJianPiaoXinXi", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectJianPiaoXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectJianPiaoXinXiAsync(string TicketMark, int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectBaoBanXinXi", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectBaoBanXinXiResponse")]
        System.Data.DataSet SelectBaoBanXinXi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectBaoBanXinXi", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectBaoBanXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectBaoBanXinXiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/UpdateSeatsState", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/UpdateSeatsStateResponse")]
        int UpdateSeatsState(int SeatsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/UpdateSeatsState", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/UpdateSeatsStateResponse")]
        System.Threading.Tasks.Task<int> UpdateSeatsStateAsync(int SeatsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectPiaoHaoByCheLiangID", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectPiaoHaoByCheLiangIDResponse")]
        System.Data.DataSet SelectPiaoHaoByCheLiangID(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JianPiaoXiTong/SelectPiaoHaoByCheLiangID", ReplyAction="http://tempuri.org/FRM_JianPiaoXiTong/SelectPiaoHaoByCheLiangIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectPiaoHaoByCheLiangIDAsync(int VehicleID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_JianPiaoXiTongChannel : 集团客运综合管理系统.BLL集团客运综合管理.InspectTicketManager.FRM_JianPiaoXiTong.FRM_JianPiaoXiTong, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_JianPiaoXiTongClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.InspectTicketManager.FRM_JianPiaoXiTong.FRM_JianPiaoXiTong>, 集团客运综合管理系统.BLL集团客运综合管理.InspectTicketManager.FRM_JianPiaoXiTong.FRM_JianPiaoXiTong {
        
        public FRM_JianPiaoXiTongClient() {
        }
        
        public FRM_JianPiaoXiTongClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_JianPiaoXiTongClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JianPiaoXiTongClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JianPiaoXiTongClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SelectCheLiangBianHao() {
            return base.Channel.SelectCheLiangBianHao();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangBianHaoAsync() {
            return base.Channel.SelectCheLiangBianHaoAsync();
        }
        
        public System.Data.DataSet SelectCheLiangByCheLiangBianHao(string VehicleNumber) {
            return base.Channel.SelectCheLiangByCheLiangBianHao(VehicleNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangByCheLiangBianHaoAsync(string VehicleNumber) {
            return base.Channel.SelectCheLiangByCheLiangBianHaoAsync(VehicleNumber);
        }
        
        public System.Data.DataSet SelectCheLiangXiWeiZhangTai(int VehicleID) {
            return base.Channel.SelectCheLiangXiWeiZhangTai(VehicleID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangXiWeiZhangTaiAsync(int VehicleID) {
            return base.Channel.SelectCheLiangXiWeiZhangTaiAsync(VehicleID);
        }
        
        public System.Data.DataSet SelectDaiJianCheLiang() {
            return base.Channel.SelectDaiJianCheLiang();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectDaiJianCheLiangAsync() {
            return base.Channel.SelectDaiJianCheLiangAsync();
        }
        
        public System.Data.DataSet SelectJianPiaoXinXi(string TicketMark, int VehicleID) {
            return base.Channel.SelectJianPiaoXinXi(TicketMark, VehicleID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectJianPiaoXinXiAsync(string TicketMark, int VehicleID) {
            return base.Channel.SelectJianPiaoXinXiAsync(TicketMark, VehicleID);
        }
        
        public System.Data.DataSet SelectBaoBanXinXi() {
            return base.Channel.SelectBaoBanXinXi();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectBaoBanXinXiAsync() {
            return base.Channel.SelectBaoBanXinXiAsync();
        }
        
        public int UpdateSeatsState(int SeatsID) {
            return base.Channel.UpdateSeatsState(SeatsID);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSeatsStateAsync(int SeatsID) {
            return base.Channel.UpdateSeatsStateAsync(SeatsID);
        }
        
        public System.Data.DataSet SelectPiaoHaoByCheLiangID(int VehicleID) {
            return base.Channel.SelectPiaoHaoByCheLiangID(VehicleID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectPiaoHaoByCheLiangIDAsync(int VehicleID) {
            return base.Channel.SelectPiaoHaoByCheLiangIDAsync(VehicleID);
        }
    }
}
