//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha")]
    public interface Jinzhanjiancha {
        
        // CODEGEN: 参数“selectanquanjianxianmghuResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/selectanquanjianxianmghu", ReplyAction="http://tempuri.org/Jinzhanjiancha/selectanquanjianxianmghuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuResponse selectanquanjianxianmghu(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/selectanquanjianxianmghu", ReplyAction="http://tempuri.org/Jinzhanjiancha/selectanquanjianxianmghuResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuResponse> selectanquanjianxianmghuAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuRequest request);
        
        // CODEGEN: 参数“Comments”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/INSERTInspectionItemmingxi", ReplyAction="http://tempuri.org/Jinzhanjiancha/INSERTInspectionItemmingxiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiResponse INSERTInspectionItemmingxi(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/INSERTInspectionItemmingxi", ReplyAction="http://tempuri.org/Jinzhanjiancha/INSERTInspectionItemmingxiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiResponse> INSERTInspectionItemmingxiAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiRequest request);
        
        // CODEGEN: 参数“TheDriverSignature”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/insectjianchadan", ReplyAction="http://tempuri.org/Jinzhanjiancha/insectjianchadanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanResponse insectjianchadan(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/insectjianchadan", ReplyAction="http://tempuri.org/Jinzhanjiancha/insectjianchadanResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanResponse> insectjianchadanAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanRequest request);
        
        // CODEGEN: 参数“CarSaveCheak_SelectchelaingResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_Selectchelaing", ReplyAction="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_SelectchelaingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingResponse CarSaveCheak_Selectchelaing(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_Selectchelaing", ReplyAction="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_SelectchelaingResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingResponse> CarSaveCheak_SelectchelaingAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingRequest request);
        
        // CODEGEN: 参数“SelectCheLiangXinXiOnchepaihaoResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/SelectCheLiangXinXiOnchepaihao", ReplyAction="http://tempuri.org/Jinzhanjiancha/SelectCheLiangXinXiOnchepaihaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoResponse SelectCheLiangXinXiOnchepaihao(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/SelectCheLiangXinXiOnchepaihao", ReplyAction="http://tempuri.org/Jinzhanjiancha/SelectCheLiangXinXiOnchepaihaoResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoResponse> SelectCheLiangXinXiOnchepaihaoAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoRequest request);
        
        // CODEGEN: 参数“SELECTCEXINGONCHEPIHAOResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/SELECTCEXINGONCHEPIHAO", ReplyAction="http://tempuri.org/Jinzhanjiancha/SELECTCEXINGONCHEPIHAOResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAOResponse SELECTCEXINGONCHEPIHAO(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/SELECTCEXINGONCHEPIHAO", ReplyAction="http://tempuri.org/Jinzhanjiancha/SELECTCEXINGONCHEPIHAOResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAOResponse> SELECTCEXINGONCHEPIHAOAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAORequest request);
        
        // CODEGEN: 参数“CarSaveCheak_selectcheshudanweiResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_selectcheshudanwei", ReplyAction="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_selectcheshudanweiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiResponse CarSaveCheak_selectcheshudanwei(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_selectcheshudanwei", ReplyAction="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_selectcheshudanweiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiResponse> CarSaveCheak_selectcheshudanweiAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiRequest request);
        
        // CODEGEN: 参数“CarSaveCheak_selectjichayuanResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_selectjichayuan", ReplyAction="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_selectjichayuanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanResponse CarSaveCheak_selectjichayuan(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_selectjichayuan", ReplyAction="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_selectjichayuanResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanResponse> CarSaveCheak_selectjichayuanAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_updatechelaingzhuangtai", ReplyAction="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_updatechelaingzhuangtaiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CarSaveCheak_updatechelaingzhuangtai(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_updatechelaingzhuangtai", ReplyAction="http://tempuri.org/Jinzhanjiancha/CarSaveCheak_updatechelaingzhuangtaiResponse")]
        System.Threading.Tasks.Task<int> CarSaveCheak_updatechelaingzhuangtaiAsync(int VehicleID);
        
        // CODEGEN: 参数“selectdongtaijianchadanResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/selectdongtaijianchadan", ReplyAction="http://tempuri.org/Jinzhanjiancha/selectdongtaijianchadanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanResponse selectdongtaijianchadan(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/selectdongtaijianchadan", ReplyAction="http://tempuri.org/Jinzhanjiancha/selectdongtaijianchadanResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanResponse> selectdongtaijianchadanAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanRequest request);
        
        // CODEGEN: 参数“selectmnigxiResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/selectmnigxi", ReplyAction="http://tempuri.org/Jinzhanjiancha/selectmnigxiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiResponse selectmnigxi(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Jinzhanjiancha/selectmnigxi", ReplyAction="http://tempuri.org/Jinzhanjiancha/selectmnigxiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiResponse> selectmnigxiAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectanquanjianxianmghu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectanquanjianxianmghuRequest {
        
        public selectanquanjianxianmghuRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectanquanjianxianmghuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectanquanjianxianmghuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectanquanjianxianmghuResult;
        
        public selectanquanjianxianmghuResponse() {
        }
        
        public selectanquanjianxianmghuResponse(System.Data.DataSet selectanquanjianxianmghuResult) {
            this.selectanquanjianxianmghuResult = selectanquanjianxianmghuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="INSERTInspectionItemmingxi", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class INSERTInspectionItemmingxiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CarriageInspectionShedID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int InspectionItemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool YON;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comments;
        
        public INSERTInspectionItemmingxiRequest() {
        }
        
        public INSERTInspectionItemmingxiRequest(int CarriageInspectionShedID, int InspectionItemID, bool YON, string Comments) {
            this.CarriageInspectionShedID = CarriageInspectionShedID;
            this.InspectionItemID = InspectionItemID;
            this.YON = YON;
            this.Comments = Comments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="INSERTInspectionItemmingxiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class INSERTInspectionItemmingxiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int INSERTInspectionItemmingxiResult;
        
        public INSERTInspectionItemmingxiResponse() {
        }
        
        public INSERTInspectionItemmingxiResponse(int INSERTInspectionItemmingxiResult) {
            this.INSERTInspectionItemmingxiResult = INSERTInspectionItemmingxiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insectjianchadan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insectjianchadanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int VehicleID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int UserTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int CarBelongToTheUnitID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int CreateUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int DeleteUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TheDriverSignature;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PlateNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int VehicleTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public int CompetaterID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public System.DateTime Youxiaodate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public bool YON;
        
        public insectjianchadanRequest() {
        }
        
        public insectjianchadanRequest(int VehicleID, int UserTypeID, int CarBelongToTheUnitID, int CreateUserID, int DeleteUserID, string TheDriverSignature, string PlateNumber, int VehicleTypeID, int CompetaterID, System.DateTime Youxiaodate, bool YON) {
            this.VehicleID = VehicleID;
            this.UserTypeID = UserTypeID;
            this.CarBelongToTheUnitID = CarBelongToTheUnitID;
            this.CreateUserID = CreateUserID;
            this.DeleteUserID = DeleteUserID;
            this.TheDriverSignature = TheDriverSignature;
            this.PlateNumber = PlateNumber;
            this.VehicleTypeID = VehicleTypeID;
            this.CompetaterID = CompetaterID;
            this.Youxiaodate = Youxiaodate;
            this.YON = YON;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insectjianchadanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insectjianchadanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int insectjianchadanResult;
        
        public insectjianchadanResponse() {
        }
        
        public insectjianchadanResponse(int insectjianchadanResult) {
            this.insectjianchadanResult = insectjianchadanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarSaveCheak_Selectchelaing", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CarSaveCheak_SelectchelaingRequest {
        
        public CarSaveCheak_SelectchelaingRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarSaveCheak_SelectchelaingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CarSaveCheak_SelectchelaingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet CarSaveCheak_SelectchelaingResult;
        
        public CarSaveCheak_SelectchelaingResponse() {
        }
        
        public CarSaveCheak_SelectchelaingResponse(System.Data.DataSet CarSaveCheak_SelectchelaingResult) {
            this.CarSaveCheak_SelectchelaingResult = CarSaveCheak_SelectchelaingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectCheLiangXinXiOnchepaihao", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectCheLiangXinXiOnchepaihaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PlateNumber;
        
        public SelectCheLiangXinXiOnchepaihaoRequest() {
        }
        
        public SelectCheLiangXinXiOnchepaihaoRequest(string PlateNumber) {
            this.PlateNumber = PlateNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectCheLiangXinXiOnchepaihaoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectCheLiangXinXiOnchepaihaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectCheLiangXinXiOnchepaihaoResult;
        
        public SelectCheLiangXinXiOnchepaihaoResponse() {
        }
        
        public SelectCheLiangXinXiOnchepaihaoResponse(System.Data.DataSet SelectCheLiangXinXiOnchepaihaoResult) {
            this.SelectCheLiangXinXiOnchepaihaoResult = SelectCheLiangXinXiOnchepaihaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SELECTCEXINGONCHEPIHAO", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SELECTCEXINGONCHEPIHAORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int VehicleID;
        
        public SELECTCEXINGONCHEPIHAORequest() {
        }
        
        public SELECTCEXINGONCHEPIHAORequest(int VehicleID) {
            this.VehicleID = VehicleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SELECTCEXINGONCHEPIHAOResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SELECTCEXINGONCHEPIHAOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SELECTCEXINGONCHEPIHAOResult;
        
        public SELECTCEXINGONCHEPIHAOResponse() {
        }
        
        public SELECTCEXINGONCHEPIHAOResponse(System.Data.DataSet SELECTCEXINGONCHEPIHAOResult) {
            this.SELECTCEXINGONCHEPIHAOResult = SELECTCEXINGONCHEPIHAOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarSaveCheak_selectcheshudanwei", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CarSaveCheak_selectcheshudanweiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int VehicleID;
        
        public CarSaveCheak_selectcheshudanweiRequest() {
        }
        
        public CarSaveCheak_selectcheshudanweiRequest(int VehicleID) {
            this.VehicleID = VehicleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarSaveCheak_selectcheshudanweiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CarSaveCheak_selectcheshudanweiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet CarSaveCheak_selectcheshudanweiResult;
        
        public CarSaveCheak_selectcheshudanweiResponse() {
        }
        
        public CarSaveCheak_selectcheshudanweiResponse(System.Data.DataSet CarSaveCheak_selectcheshudanweiResult) {
            this.CarSaveCheak_selectcheshudanweiResult = CarSaveCheak_selectcheshudanweiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarSaveCheak_selectjichayuan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CarSaveCheak_selectjichayuanRequest {
        
        public CarSaveCheak_selectjichayuanRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarSaveCheak_selectjichayuanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CarSaveCheak_selectjichayuanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet CarSaveCheak_selectjichayuanResult;
        
        public CarSaveCheak_selectjichayuanResponse() {
        }
        
        public CarSaveCheak_selectjichayuanResponse(System.Data.DataSet CarSaveCheak_selectjichayuanResult) {
            this.CarSaveCheak_selectjichayuanResult = CarSaveCheak_selectjichayuanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectdongtaijianchadan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectdongtaijianchadanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PlateNumber;
        
        public selectdongtaijianchadanRequest() {
        }
        
        public selectdongtaijianchadanRequest(string PlateNumber) {
            this.PlateNumber = PlateNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectdongtaijianchadanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectdongtaijianchadanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectdongtaijianchadanResult;
        
        public selectdongtaijianchadanResponse() {
        }
        
        public selectdongtaijianchadanResponse(System.Data.DataSet selectdongtaijianchadanResult) {
            this.selectdongtaijianchadanResult = selectdongtaijianchadanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectmnigxi", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectmnigxiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CarriageInspectionShedID;
        
        public selectmnigxiRequest() {
        }
        
        public selectmnigxiRequest(int CarriageInspectionShedID) {
            this.CarriageInspectionShedID = CarriageInspectionShedID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectmnigxiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectmnigxiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectmnigxiResult;
        
        public selectmnigxiResponse() {
        }
        
        public selectmnigxiResponse(System.Data.DataSet selectmnigxiResult) {
            this.selectmnigxiResult = selectmnigxiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JinzhanjianchaChannel : 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JinzhanjianchaClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha>, 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha {
        
        public JinzhanjianchaClient() {
        }
        
        public JinzhanjianchaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JinzhanjianchaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JinzhanjianchaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JinzhanjianchaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuResponse 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.selectanquanjianxianmghu(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuRequest request) {
            return base.Channel.selectanquanjianxianmghu(request);
        }
        
        public System.Data.DataSet selectanquanjianxianmghu() {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuRequest();
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).selectanquanjianxianmghu(inValue);
            return retVal.selectanquanjianxianmghuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuResponse> 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.selectanquanjianxianmghuAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuRequest request) {
            return base.Channel.selectanquanjianxianmghuAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuResponse> selectanquanjianxianmghuAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectanquanjianxianmghuRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).selectanquanjianxianmghuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiResponse 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.INSERTInspectionItemmingxi(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiRequest request) {
            return base.Channel.INSERTInspectionItemmingxi(request);
        }
        
        public int INSERTInspectionItemmingxi(int CarriageInspectionShedID, int InspectionItemID, bool YON, string Comments) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiRequest();
            inValue.CarriageInspectionShedID = CarriageInspectionShedID;
            inValue.InspectionItemID = InspectionItemID;
            inValue.YON = YON;
            inValue.Comments = Comments;
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).INSERTInspectionItemmingxi(inValue);
            return retVal.INSERTInspectionItemmingxiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiResponse> 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.INSERTInspectionItemmingxiAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiRequest request) {
            return base.Channel.INSERTInspectionItemmingxiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiResponse> INSERTInspectionItemmingxiAsync(int CarriageInspectionShedID, int InspectionItemID, bool YON, string Comments) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.INSERTInspectionItemmingxiRequest();
            inValue.CarriageInspectionShedID = CarriageInspectionShedID;
            inValue.InspectionItemID = InspectionItemID;
            inValue.YON = YON;
            inValue.Comments = Comments;
            return ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).INSERTInspectionItemmingxiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanResponse 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.insectjianchadan(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanRequest request) {
            return base.Channel.insectjianchadan(request);
        }
        
        public int insectjianchadan(int VehicleID, int UserTypeID, int CarBelongToTheUnitID, int CreateUserID, int DeleteUserID, string TheDriverSignature, string PlateNumber, int VehicleTypeID, int CompetaterID, System.DateTime Youxiaodate, bool YON) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanRequest();
            inValue.VehicleID = VehicleID;
            inValue.UserTypeID = UserTypeID;
            inValue.CarBelongToTheUnitID = CarBelongToTheUnitID;
            inValue.CreateUserID = CreateUserID;
            inValue.DeleteUserID = DeleteUserID;
            inValue.TheDriverSignature = TheDriverSignature;
            inValue.PlateNumber = PlateNumber;
            inValue.VehicleTypeID = VehicleTypeID;
            inValue.CompetaterID = CompetaterID;
            inValue.Youxiaodate = Youxiaodate;
            inValue.YON = YON;
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).insectjianchadan(inValue);
            return retVal.insectjianchadanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanResponse> 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.insectjianchadanAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanRequest request) {
            return base.Channel.insectjianchadanAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanResponse> insectjianchadanAsync(int VehicleID, int UserTypeID, int CarBelongToTheUnitID, int CreateUserID, int DeleteUserID, string TheDriverSignature, string PlateNumber, int VehicleTypeID, int CompetaterID, System.DateTime Youxiaodate, bool YON) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.insectjianchadanRequest();
            inValue.VehicleID = VehicleID;
            inValue.UserTypeID = UserTypeID;
            inValue.CarBelongToTheUnitID = CarBelongToTheUnitID;
            inValue.CreateUserID = CreateUserID;
            inValue.DeleteUserID = DeleteUserID;
            inValue.TheDriverSignature = TheDriverSignature;
            inValue.PlateNumber = PlateNumber;
            inValue.VehicleTypeID = VehicleTypeID;
            inValue.CompetaterID = CompetaterID;
            inValue.Youxiaodate = Youxiaodate;
            inValue.YON = YON;
            return ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).insectjianchadanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingResponse 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.CarSaveCheak_Selectchelaing(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingRequest request) {
            return base.Channel.CarSaveCheak_Selectchelaing(request);
        }
        
        public System.Data.DataSet CarSaveCheak_Selectchelaing() {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingRequest();
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).CarSaveCheak_Selectchelaing(inValue);
            return retVal.CarSaveCheak_SelectchelaingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingResponse> 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.CarSaveCheak_SelectchelaingAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingRequest request) {
            return base.Channel.CarSaveCheak_SelectchelaingAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingResponse> CarSaveCheak_SelectchelaingAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_SelectchelaingRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).CarSaveCheak_SelectchelaingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoResponse 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihao(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoRequest request) {
            return base.Channel.SelectCheLiangXinXiOnchepaihao(request);
        }
        
        public System.Data.DataSet SelectCheLiangXinXiOnchepaihao(string PlateNumber) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoRequest();
            inValue.PlateNumber = PlateNumber;
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).SelectCheLiangXinXiOnchepaihao(inValue);
            return retVal.SelectCheLiangXinXiOnchepaihaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoResponse> 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoRequest request) {
            return base.Channel.SelectCheLiangXinXiOnchepaihaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoResponse> SelectCheLiangXinXiOnchepaihaoAsync(string PlateNumber) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SelectCheLiangXinXiOnchepaihaoRequest();
            inValue.PlateNumber = PlateNumber;
            return ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).SelectCheLiangXinXiOnchepaihaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAOResponse 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.SELECTCEXINGONCHEPIHAO(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAORequest request) {
            return base.Channel.SELECTCEXINGONCHEPIHAO(request);
        }
        
        public System.Data.DataSet SELECTCEXINGONCHEPIHAO(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAORequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAORequest();
            inValue.VehicleID = VehicleID;
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAOResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).SELECTCEXINGONCHEPIHAO(inValue);
            return retVal.SELECTCEXINGONCHEPIHAOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAOResponse> 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.SELECTCEXINGONCHEPIHAOAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAORequest request) {
            return base.Channel.SELECTCEXINGONCHEPIHAOAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAOResponse> SELECTCEXINGONCHEPIHAOAsync(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAORequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.SELECTCEXINGONCHEPIHAORequest();
            inValue.VehicleID = VehicleID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).SELECTCEXINGONCHEPIHAOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiResponse 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.CarSaveCheak_selectcheshudanwei(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiRequest request) {
            return base.Channel.CarSaveCheak_selectcheshudanwei(request);
        }
        
        public System.Data.DataSet CarSaveCheak_selectcheshudanwei(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiRequest();
            inValue.VehicleID = VehicleID;
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).CarSaveCheak_selectcheshudanwei(inValue);
            return retVal.CarSaveCheak_selectcheshudanweiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiResponse> 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiRequest request) {
            return base.Channel.CarSaveCheak_selectcheshudanweiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiResponse> CarSaveCheak_selectcheshudanweiAsync(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectcheshudanweiRequest();
            inValue.VehicleID = VehicleID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).CarSaveCheak_selectcheshudanweiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanResponse 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.CarSaveCheak_selectjichayuan(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanRequest request) {
            return base.Channel.CarSaveCheak_selectjichayuan(request);
        }
        
        public System.Data.DataSet CarSaveCheak_selectjichayuan() {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanRequest();
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).CarSaveCheak_selectjichayuan(inValue);
            return retVal.CarSaveCheak_selectjichayuanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanResponse> 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.CarSaveCheak_selectjichayuanAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanRequest request) {
            return base.Channel.CarSaveCheak_selectjichayuanAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanResponse> CarSaveCheak_selectjichayuanAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.CarSaveCheak_selectjichayuanRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).CarSaveCheak_selectjichayuanAsync(inValue);
        }
        
        public int CarSaveCheak_updatechelaingzhuangtai(int VehicleID) {
            return base.Channel.CarSaveCheak_updatechelaingzhuangtai(VehicleID);
        }
        
        public System.Threading.Tasks.Task<int> CarSaveCheak_updatechelaingzhuangtaiAsync(int VehicleID) {
            return base.Channel.CarSaveCheak_updatechelaingzhuangtaiAsync(VehicleID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanResponse 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.selectdongtaijianchadan(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanRequest request) {
            return base.Channel.selectdongtaijianchadan(request);
        }
        
        public System.Data.DataSet selectdongtaijianchadan(string PlateNumber) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanRequest();
            inValue.PlateNumber = PlateNumber;
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).selectdongtaijianchadan(inValue);
            return retVal.selectdongtaijianchadanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanResponse> 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.selectdongtaijianchadanAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanRequest request) {
            return base.Channel.selectdongtaijianchadanAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanResponse> selectdongtaijianchadanAsync(string PlateNumber) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectdongtaijianchadanRequest();
            inValue.PlateNumber = PlateNumber;
            return ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).selectdongtaijianchadanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiResponse 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.selectmnigxi(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiRequest request) {
            return base.Channel.selectmnigxi(request);
        }
        
        public System.Data.DataSet selectmnigxi(int CarriageInspectionShedID) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiRequest();
            inValue.CarriageInspectionShedID = CarriageInspectionShedID;
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).selectmnigxi(inValue);
            return retVal.selectmnigxiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiResponse> 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha.selectmnigxiAsync(集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiRequest request) {
            return base.Channel.selectmnigxiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiResponse> selectmnigxiAsync(int CarriageInspectionShedID) {
            集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.selectmnigxiRequest();
            inValue.CarriageInspectionShedID = CarriageInspectionShedID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.进站检查.Jinzhanjiancha.Jinzhanjiancha)(this)).selectmnigxiAsync(inValue);
        }
    }
}
