//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.UserManager.FRM_YonHuQuanXianGuanLi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.UserManager.FRM_YonHuQuanXianGuanLi.FRM_YonHuQuanXianGuanLi")]
    public interface FRM_YonHuQuanXianGuanLi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectAuthorityTypeFuID", ReplyAction="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectAuthorityTypeFuIDResponse")]
        System.Data.DataSet SelectAuthorityTypeFuID(int AuthorityTypeFuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectAuthorityTypeFuID", ReplyAction="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectAuthorityTypeFuIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectAuthorityTypeFuIDAsync(int AuthorityTypeFuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectUserType", ReplyAction="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectUserTypeResponse")]
        System.Data.DataSet SelectUserType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectUserType", ReplyAction="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectUserTypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectUserTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectCarStandFuID", ReplyAction="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectCarStandFuIDResponse")]
        System.Data.DataSet SelectCarStandFuID(int CarStandFuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectCarStandFuID", ReplyAction="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SelectCarStandFuIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCarStandFuIDAsync(int CarStandFuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SDFSFSF", ReplyAction="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SDFSFSFResponse")]
        System.Data.DataSet SDFSFSF(int 系统管理FU);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SDFSFSF", ReplyAction="http://tempuri.org/FRM_YonHuQuanXianGuanLi/SDFSFSFResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SDFSFSFAsync(int 系统管理FU);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_YonHuQuanXianGuanLiChannel : 集团客运综合管理系统.BLL集团客运综合管理.UserManager.FRM_YonHuQuanXianGuanLi.FRM_YonHuQuanXianGuanLi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_YonHuQuanXianGuanLiClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.UserManager.FRM_YonHuQuanXianGuanLi.FRM_YonHuQuanXianGuanLi>, 集团客运综合管理系统.BLL集团客运综合管理.UserManager.FRM_YonHuQuanXianGuanLi.FRM_YonHuQuanXianGuanLi {
        
        public FRM_YonHuQuanXianGuanLiClient() {
        }
        
        public FRM_YonHuQuanXianGuanLiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_YonHuQuanXianGuanLiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_YonHuQuanXianGuanLiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_YonHuQuanXianGuanLiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SelectAuthorityTypeFuID(int AuthorityTypeFuID) {
            return base.Channel.SelectAuthorityTypeFuID(AuthorityTypeFuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectAuthorityTypeFuIDAsync(int AuthorityTypeFuID) {
            return base.Channel.SelectAuthorityTypeFuIDAsync(AuthorityTypeFuID);
        }
        
        public System.Data.DataSet SelectUserType() {
            return base.Channel.SelectUserType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectUserTypeAsync() {
            return base.Channel.SelectUserTypeAsync();
        }
        
        public System.Data.DataSet SelectCarStandFuID(int CarStandFuID) {
            return base.Channel.SelectCarStandFuID(CarStandFuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCarStandFuIDAsync(int CarStandFuID) {
            return base.Channel.SelectCarStandFuIDAsync(CarStandFuID);
        }
        
        public System.Data.DataSet SDFSFSF(int 系统管理FU) {
            return base.Channel.SDFSFSF(系统管理FU);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SDFSFSFAsync(int 系统管理FU) {
            return base.Channel.SDFSFSFAsync(系统管理FU);
        }
    }
}
