//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_CheLiangGuangLi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.VehicleManage.FRM_CheLiangGuangLi.FRM_CheLiangGuangLi")]
    public interface FRM_CheLiangGuangLi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangBianHao", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangBianHaoResponse")]
        System.Data.DataSet SelectCheLiangBianHao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangBianHao", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangBianHaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangBianHaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXiResponse")]
        System.Data.DataSet SelectCheLiangXinXi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangXinXiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXiByVehiclePaiNumber", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXiByVehiclePaiNumberRespo" +
            "nse")]
        System.Data.DataSet SelectCheLiangXinXiByVehiclePaiNumber(string VehiclePaiNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXiByVehiclePaiNumber", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXiByVehiclePaiNumberRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangXinXiByVehiclePaiNumberAsync(string VehiclePaiNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXiByVehicleNumber", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXiByVehicleNumberResponse" +
            "")]
        System.Data.DataSet SelectCheLiangXinXiByVehicleNumber(string VehicleNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXiByVehicleNumber", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangXinXiByVehicleNumberResponse" +
            "")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangXinXiByVehicleNumberAsync(string VehicleNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangMingXiXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangMingXiXinXiResponse")]
        System.Data.DataSet SelectCheLiangMingXiXinXi(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangMingXiXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/SelectCheLiangMingXiXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangMingXiXinXiAsync(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheZhuXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheZhuXinXiResponse")]
        int DeleteCheZhuXinXi(int VehicleHostID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheZhuXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheZhuXinXiResponse")]
        System.Threading.Tasks.Task<int> DeleteCheZhuXinXiAsync(int VehicleHostID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/DeleteBaoXianXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/DeleteBaoXianXinXiResponse")]
        int DeleteBaoXianXinXi(int PolicyOfInsuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/DeleteBaoXianXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/DeleteBaoXianXinXiResponse")]
        System.Threading.Tasks.Task<int> DeleteBaoXianXinXiAsync(int PolicyOfInsuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheLiangZhengJianXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheLiangZhengJianXinXiResponse")]
        int DeleteCheLiangZhengJianXinXi(int VehicleLicenseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheLiangZhengJianXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheLiangZhengJianXinXiResponse")]
        System.Threading.Tasks.Task<int> DeleteCheLiangZhengJianXinXiAsync(int VehicleLicenseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheLiangXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheLiangXinXiResponse")]
        int DeleteCheLiangXinXi(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheLiangXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/DeleteCheLiangXinXiResponse")]
        System.Threading.Tasks.Task<int> DeleteCheLiangXinXiAsync(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/DeleteXiWei", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/DeleteXiWeiResponse")]
        int DeleteXiWei(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi/DeleteXiWei", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi/DeleteXiWeiResponse")]
        System.Threading.Tasks.Task<int> DeleteXiWeiAsync(int VehicleID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_CheLiangGuangLiChannel : 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_CheLiangGuangLi.FRM_CheLiangGuangLi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_CheLiangGuangLiClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_CheLiangGuangLi.FRM_CheLiangGuangLi>, 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_CheLiangGuangLi.FRM_CheLiangGuangLi {
        
        public FRM_CheLiangGuangLiClient() {
        }
        
        public FRM_CheLiangGuangLiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_CheLiangGuangLiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_CheLiangGuangLiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_CheLiangGuangLiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SelectCheLiangBianHao() {
            return base.Channel.SelectCheLiangBianHao();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangBianHaoAsync() {
            return base.Channel.SelectCheLiangBianHaoAsync();
        }
        
        public System.Data.DataSet SelectCheLiangXinXi() {
            return base.Channel.SelectCheLiangXinXi();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangXinXiAsync() {
            return base.Channel.SelectCheLiangXinXiAsync();
        }
        
        public System.Data.DataSet SelectCheLiangXinXiByVehiclePaiNumber(string VehiclePaiNumber) {
            return base.Channel.SelectCheLiangXinXiByVehiclePaiNumber(VehiclePaiNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangXinXiByVehiclePaiNumberAsync(string VehiclePaiNumber) {
            return base.Channel.SelectCheLiangXinXiByVehiclePaiNumberAsync(VehiclePaiNumber);
        }
        
        public System.Data.DataSet SelectCheLiangXinXiByVehicleNumber(string VehicleNumber) {
            return base.Channel.SelectCheLiangXinXiByVehicleNumber(VehicleNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangXinXiByVehicleNumberAsync(string VehicleNumber) {
            return base.Channel.SelectCheLiangXinXiByVehicleNumberAsync(VehicleNumber);
        }
        
        public System.Data.DataSet SelectCheLiangMingXiXinXi(int VehicleID) {
            return base.Channel.SelectCheLiangMingXiXinXi(VehicleID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangMingXiXinXiAsync(int VehicleID) {
            return base.Channel.SelectCheLiangMingXiXinXiAsync(VehicleID);
        }
        
        public int DeleteCheZhuXinXi(int VehicleHostID) {
            return base.Channel.DeleteCheZhuXinXi(VehicleHostID);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCheZhuXinXiAsync(int VehicleHostID) {
            return base.Channel.DeleteCheZhuXinXiAsync(VehicleHostID);
        }
        
        public int DeleteBaoXianXinXi(int PolicyOfInsuranceID) {
            return base.Channel.DeleteBaoXianXinXi(PolicyOfInsuranceID);
        }
        
        public System.Threading.Tasks.Task<int> DeleteBaoXianXinXiAsync(int PolicyOfInsuranceID) {
            return base.Channel.DeleteBaoXianXinXiAsync(PolicyOfInsuranceID);
        }
        
        public int DeleteCheLiangZhengJianXinXi(int VehicleLicenseID) {
            return base.Channel.DeleteCheLiangZhengJianXinXi(VehicleLicenseID);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCheLiangZhengJianXinXiAsync(int VehicleLicenseID) {
            return base.Channel.DeleteCheLiangZhengJianXinXiAsync(VehicleLicenseID);
        }
        
        public int DeleteCheLiangXinXi(int VehicleID) {
            return base.Channel.DeleteCheLiangXinXi(VehicleID);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCheLiangXinXiAsync(int VehicleID) {
            return base.Channel.DeleteCheLiangXinXiAsync(VehicleID);
        }
        
        public int DeleteXiWei(int VehicleID) {
            return base.Channel.DeleteXiWei(VehicleID);
        }
        
        public System.Threading.Tasks.Task<int> DeleteXiWeiAsync(int VehicleID) {
            return base.Channel.DeleteXiWeiAsync(VehicleID);
        }
    }
}
