//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_JiaShiYuanGuanLi_Insert {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.VehicleManage.FRM_JiaShiYuanGuanLi_Insert.FRM_JiaShiYuanGuanLi_Insert" +
        "")]
    public interface FRM_JiaShiYuanGuanLi_Insert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SelectQuasiDrivingType", ReplyAction="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SelectQuasiDrivingTypeResponse")]
        System.Data.DataSet SelectQuasiDrivingType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SelectQuasiDrivingType", ReplyAction="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SelectQuasiDrivingTypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectQuasiDrivingTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SelectOrganization", ReplyAction="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SelectOrganizationResponse")]
        System.Data.DataSet SelectOrganization();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SelectOrganization", ReplyAction="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SelectOrganizationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectOrganizationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/InsertJiaShiYuanXinXi", ReplyAction="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/InsertJiaShiYuanXinXiResponse")]
        int InsertJiaShiYuanXinXi(
                    int QuasiDrivingTypeID, 
                    int OrganizationID, 
                    int CreateUserID, 
                    int DeleteUserID, 
                    string DriverMC, 
                    string Sex, 
                    string Identification, 
                    string ContactPhone, 
                    int DriveAge, 
                    string DrivingLicenseNo, 
                    string DriverNumber, 
                    string Certificate, 
                    System.DateTime DrivingLicence, 
                    System.DateTime licensePeriod, 
                    string DriverVehicleNumber, 
                    System.DateTime CertificateLicence, 
                    byte[] Photo, 
                    string Comment, 
                    bool JobON, 
                    System.DateTime CreateTime, 
                    System.DateTime LogicalDeleteTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/InsertJiaShiYuanXinXi", ReplyAction="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/InsertJiaShiYuanXinXiResponse")]
        System.Threading.Tasks.Task<int> InsertJiaShiYuanXinXiAsync(
                    int QuasiDrivingTypeID, 
                    int OrganizationID, 
                    int CreateUserID, 
                    int DeleteUserID, 
                    string DriverMC, 
                    string Sex, 
                    string Identification, 
                    string ContactPhone, 
                    int DriveAge, 
                    string DrivingLicenseNo, 
                    string DriverNumber, 
                    string Certificate, 
                    System.DateTime DrivingLicence, 
                    System.DateTime licensePeriod, 
                    string DriverVehicleNumber, 
                    System.DateTime CertificateLicence, 
                    byte[] Photo, 
                    string Comment, 
                    bool JobON, 
                    System.DateTime CreateTime, 
                    System.DateTime LogicalDeleteTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SELECT", ReplyAction="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SELECTResponse")]
        int SELECT(byte[] Photo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SELECT", ReplyAction="http://tempuri.org/FRM_JiaShiYuanGuanLi_Insert/SELECTResponse")]
        System.Threading.Tasks.Task<int> SELECTAsync(byte[] Photo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_JiaShiYuanGuanLi_InsertChannel : 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_JiaShiYuanGuanLi_Insert.FRM_JiaShiYuanGuanLi_Insert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_JiaShiYuanGuanLi_InsertClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_JiaShiYuanGuanLi_Insert.FRM_JiaShiYuanGuanLi_Insert>, 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_JiaShiYuanGuanLi_Insert.FRM_JiaShiYuanGuanLi_Insert {
        
        public FRM_JiaShiYuanGuanLi_InsertClient() {
        }
        
        public FRM_JiaShiYuanGuanLi_InsertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_JiaShiYuanGuanLi_InsertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JiaShiYuanGuanLi_InsertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JiaShiYuanGuanLi_InsertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SelectQuasiDrivingType() {
            return base.Channel.SelectQuasiDrivingType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectQuasiDrivingTypeAsync() {
            return base.Channel.SelectQuasiDrivingTypeAsync();
        }
        
        public System.Data.DataSet SelectOrganization() {
            return base.Channel.SelectOrganization();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectOrganizationAsync() {
            return base.Channel.SelectOrganizationAsync();
        }
        
        public int InsertJiaShiYuanXinXi(
                    int QuasiDrivingTypeID, 
                    int OrganizationID, 
                    int CreateUserID, 
                    int DeleteUserID, 
                    string DriverMC, 
                    string Sex, 
                    string Identification, 
                    string ContactPhone, 
                    int DriveAge, 
                    string DrivingLicenseNo, 
                    string DriverNumber, 
                    string Certificate, 
                    System.DateTime DrivingLicence, 
                    System.DateTime licensePeriod, 
                    string DriverVehicleNumber, 
                    System.DateTime CertificateLicence, 
                    byte[] Photo, 
                    string Comment, 
                    bool JobON, 
                    System.DateTime CreateTime, 
                    System.DateTime LogicalDeleteTime) {
            return base.Channel.InsertJiaShiYuanXinXi(QuasiDrivingTypeID, OrganizationID, CreateUserID, DeleteUserID, DriverMC, Sex, Identification, ContactPhone, DriveAge, DrivingLicenseNo, DriverNumber, Certificate, DrivingLicence, licensePeriod, DriverVehicleNumber, CertificateLicence, Photo, Comment, JobON, CreateTime, LogicalDeleteTime);
        }
        
        public System.Threading.Tasks.Task<int> InsertJiaShiYuanXinXiAsync(
                    int QuasiDrivingTypeID, 
                    int OrganizationID, 
                    int CreateUserID, 
                    int DeleteUserID, 
                    string DriverMC, 
                    string Sex, 
                    string Identification, 
                    string ContactPhone, 
                    int DriveAge, 
                    string DrivingLicenseNo, 
                    string DriverNumber, 
                    string Certificate, 
                    System.DateTime DrivingLicence, 
                    System.DateTime licensePeriod, 
                    string DriverVehicleNumber, 
                    System.DateTime CertificateLicence, 
                    byte[] Photo, 
                    string Comment, 
                    bool JobON, 
                    System.DateTime CreateTime, 
                    System.DateTime LogicalDeleteTime) {
            return base.Channel.InsertJiaShiYuanXinXiAsync(QuasiDrivingTypeID, OrganizationID, CreateUserID, DeleteUserID, DriverMC, Sex, Identification, ContactPhone, DriveAge, DrivingLicenseNo, DriverNumber, Certificate, DrivingLicence, licensePeriod, DriverVehicleNumber, CertificateLicence, Photo, Comment, JobON, CreateTime, LogicalDeleteTime);
        }
        
        public int SELECT(byte[] Photo) {
            return base.Channel.SELECT(Photo);
        }
        
        public System.Threading.Tasks.Task<int> SELECTAsync(byte[] Photo) {
            return base.Channel.SELECTAsync(Photo);
        }
    }
}
