//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha")]
    public interface chezhanjicha {
        
        // CODEGEN: 参数“SelectchelaingResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/Selectchelaing", ReplyAction="http://tempuri.org/chezhanjicha/SelectchelaingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingResponse Selectchelaing(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/Selectchelaing", ReplyAction="http://tempuri.org/chezhanjicha/SelectchelaingResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingResponse> SelectchelaingAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingRequest request);
        
        // CODEGEN: 参数“SelectchelaingIDResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/SelectchelaingID", ReplyAction="http://tempuri.org/chezhanjicha/SelectchelaingIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDResponse SelectchelaingID(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/SelectchelaingID", ReplyAction="http://tempuri.org/chezhanjicha/SelectchelaingIDResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDResponse> SelectchelaingIDAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDRequest request);
        
        // CODEGEN: 参数“SelectchelaingxinhaoResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/Selectchelaingxinhao", ReplyAction="http://tempuri.org/chezhanjicha/SelectchelaingxinhaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoResponse Selectchelaingxinhao(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/Selectchelaingxinhao", ReplyAction="http://tempuri.org/chezhanjicha/SelectchelaingxinhaoResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoResponse> SelectchelaingxinhaoAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoRequest request);
        
        // CODEGEN: 参数“selectbanciResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectbanci", ReplyAction="http://tempuri.org/chezhanjicha/selectbanciResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciResponse selectbanci(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectbanci", ReplyAction="http://tempuri.org/chezhanjicha/selectbanciResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciResponse> selectbanciAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciRequest request);
        
        // CODEGEN: 参数“selectbancirenshuResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectbancirenshu", ReplyAction="http://tempuri.org/chezhanjicha/selectbancirenshuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuResponse selectbancirenshu(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectbancirenshu", ReplyAction="http://tempuri.org/chezhanjicha/selectbancirenshuResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuResponse> selectbancirenshuAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuRequest request);
        
        // CODEGEN: 参数“selectbancirenshuertongshuResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectbancirenshuertongshu", ReplyAction="http://tempuri.org/chezhanjicha/selectbancirenshuertongshuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuResponse selectbancirenshuertongshu(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectbancirenshuertongshu", ReplyAction="http://tempuri.org/chezhanjicha/selectbancirenshuertongshuResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuResponse> selectbancirenshuertongshuAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuRequest request);
        
        // CODEGEN: 参数“ComprehensiveResults”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/INSERTchuzhanxinxi", ReplyAction="http://tempuri.org/chezhanjicha/INSERTchuzhanxinxiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiResponse INSERTchuzhanxinxi(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/INSERTchuzhanxinxi", ReplyAction="http://tempuri.org/chezhanjicha/INSERTchuzhanxinxiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiResponse> INSERTchuzhanxinxiAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiRequest request);
        
        // CODEGEN: 参数“selectjichayuanResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectjichayuan", ReplyAction="http://tempuri.org/chezhanjicha/selectjichayuanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanResponse selectjichayuan(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectjichayuan", ReplyAction="http://tempuri.org/chezhanjicha/selectjichayuanResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanResponse> selectjichayuanAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanRequest request);
        
        // CODEGEN: 参数“selectcheshudanweiResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectcheshudanwei", ReplyAction="http://tempuri.org/chezhanjicha/selectcheshudanweiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiResponse selectcheshudanwei(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectcheshudanwei", ReplyAction="http://tempuri.org/chezhanjicha/selectcheshudanweiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiResponse> selectcheshudanweiAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/insectchuzhanmingxi", ReplyAction="http://tempuri.org/chezhanjicha/insectchuzhanmingxiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insectchuzhanmingxi(int TheStationInspectionID, int CreateUserID, int DeleteUserID, int AuditByComparisonNaneID, bool YON, System.DateTime CreateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/insectchuzhanmingxi", ReplyAction="http://tempuri.org/chezhanjicha/insectchuzhanmingxiResponse")]
        System.Threading.Tasks.Task<int> insectchuzhanmingxiAsync(int TheStationInspectionID, int CreateUserID, int DeleteUserID, int AuditByComparisonNaneID, bool YON, System.DateTime CreateTime);
        
        // CODEGEN: 参数“selectjichaxianmuResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectjichaxianmu", ReplyAction="http://tempuri.org/chezhanjicha/selectjichaxianmuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuResponse selectjichaxianmu(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectjichaxianmu", ReplyAction="http://tempuri.org/chezhanjicha/selectjichaxianmuResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuResponse> selectjichaxianmuAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/updatechelaingzhuangtai", ReplyAction="http://tempuri.org/chezhanjicha/updatechelaingzhuangtaiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int updatechelaingzhuangtai(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/updatechelaingzhuangtai", ReplyAction="http://tempuri.org/chezhanjicha/updatechelaingzhuangtaiResponse")]
        System.Threading.Tasks.Task<int> updatechelaingzhuangtaiAsync(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/updatechelaingzhuangtaizuowei", ReplyAction="http://tempuri.org/chezhanjicha/updatechelaingzhuangtaizuoweiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int updatechelaingzhuangtaizuowei(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/updatechelaingzhuangtaizuowei", ReplyAction="http://tempuri.org/chezhanjicha/updatechelaingzhuangtaizuoweiResponse")]
        System.Threading.Tasks.Task<int> updatechelaingzhuangtaizuoweiAsync(int VehicleID);
        
        // CODEGEN: 参数“selectjichaxiangmuResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectjichaxiangmu", ReplyAction="http://tempuri.org/chezhanjicha/selectjichaxiangmuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuResponse selectjichaxiangmu(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectjichaxiangmu", ReplyAction="http://tempuri.org/chezhanjicha/selectjichaxiangmuResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuResponse> selectjichaxiangmuAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuRequest request);
        
        // CODEGEN: 参数“SELECTJICHAXIANGMUMINGXIResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/SELECTJICHAXIANGMUMINGXI", ReplyAction="http://tempuri.org/chezhanjicha/SELECTJICHAXIANGMUMINGXIResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIResponse SELECTJICHAXIANGMUMINGXI(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/SELECTJICHAXIANGMUMINGXI", ReplyAction="http://tempuri.org/chezhanjicha/SELECTJICHAXIANGMUMINGXIResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIResponse> SELECTJICHAXIANGMUMINGXIAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIRequest request);
        
        // CODEGEN: 参数“selectcheliangjichadanResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectcheliangjichadan", ReplyAction="http://tempuri.org/chezhanjicha/selectcheliangjichadanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanResponse selectcheliangjichadan(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chezhanjicha/selectcheliangjichadan", ReplyAction="http://tempuri.org/chezhanjicha/selectcheliangjichadanResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanResponse> selectcheliangjichadanAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Selectchelaing", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectchelaingRequest {
        
        public SelectchelaingRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectchelaingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectchelaingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectchelaingResult;
        
        public SelectchelaingResponse() {
        }
        
        public SelectchelaingResponse(System.Data.DataSet SelectchelaingResult) {
            this.SelectchelaingResult = SelectchelaingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectchelaingID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectchelaingIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PlateNumber;
        
        public SelectchelaingIDRequest() {
        }
        
        public SelectchelaingIDRequest(string PlateNumber) {
            this.PlateNumber = PlateNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectchelaingIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectchelaingIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectchelaingIDResult;
        
        public SelectchelaingIDResponse() {
        }
        
        public SelectchelaingIDResponse(System.Data.DataSet SelectchelaingIDResult) {
            this.SelectchelaingIDResult = SelectchelaingIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Selectchelaingxinhao", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectchelaingxinhaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int VehicleID;
        
        public SelectchelaingxinhaoRequest() {
        }
        
        public SelectchelaingxinhaoRequest(int VehicleID) {
            this.VehicleID = VehicleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectchelaingxinhaoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectchelaingxinhaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectchelaingxinhaoResult;
        
        public SelectchelaingxinhaoResponse() {
        }
        
        public SelectchelaingxinhaoResponse(System.Data.DataSet SelectchelaingxinhaoResult) {
            this.SelectchelaingxinhaoResult = SelectchelaingxinhaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectbanci", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectbanciRequest {
        
        public selectbanciRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectbanciResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectbanciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectbanciResult;
        
        public selectbanciResponse() {
        }
        
        public selectbanciResponse(System.Data.DataSet selectbanciResult) {
            this.selectbanciResult = selectbanciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectbancirenshu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectbancirenshuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int VehicleID;
        
        public selectbancirenshuRequest() {
        }
        
        public selectbancirenshuRequest(int VehicleID) {
            this.VehicleID = VehicleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectbancirenshuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectbancirenshuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectbancirenshuResult;
        
        public selectbancirenshuResponse() {
        }
        
        public selectbancirenshuResponse(System.Data.DataSet selectbancirenshuResult) {
            this.selectbancirenshuResult = selectbancirenshuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectbancirenshuertongshu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectbancirenshuertongshuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int VehicleID;
        
        public selectbancirenshuertongshuRequest() {
        }
        
        public selectbancirenshuertongshuRequest(int VehicleID) {
            this.VehicleID = VehicleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectbancirenshuertongshuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectbancirenshuertongshuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectbancirenshuertongshuResult;
        
        public selectbancirenshuertongshuResponse() {
        }
        
        public selectbancirenshuertongshuResponse(System.Data.DataSet selectbancirenshuertongshuResult) {
            this.selectbancirenshuertongshuResult = selectbancirenshuertongshuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="INSERTchuzhanxinxi", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class INSERTchuzhanxinxiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int VehicleID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CarBelongToTheUnitID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int CreateUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int DeleteUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int TheNumberOfPassengers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int ChildrenFree;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ComprehensiveResults;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public bool AllPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public System.DateTime CreateTime;
        
        public INSERTchuzhanxinxiRequest() {
        }
        
        public INSERTchuzhanxinxiRequest(int VehicleID, int CarBelongToTheUnitID, int UserID, int CreateUserID, int DeleteUserID, int TheNumberOfPassengers, int ChildrenFree, string ComprehensiveResults, bool AllPass, System.DateTime CreateTime) {
            this.VehicleID = VehicleID;
            this.CarBelongToTheUnitID = CarBelongToTheUnitID;
            this.UserID = UserID;
            this.CreateUserID = CreateUserID;
            this.DeleteUserID = DeleteUserID;
            this.TheNumberOfPassengers = TheNumberOfPassengers;
            this.ChildrenFree = ChildrenFree;
            this.ComprehensiveResults = ComprehensiveResults;
            this.AllPass = AllPass;
            this.CreateTime = CreateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="INSERTchuzhanxinxiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class INSERTchuzhanxinxiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int INSERTchuzhanxinxiResult;
        
        public INSERTchuzhanxinxiResponse() {
        }
        
        public INSERTchuzhanxinxiResponse(int INSERTchuzhanxinxiResult) {
            this.INSERTchuzhanxinxiResult = INSERTchuzhanxinxiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectjichayuan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectjichayuanRequest {
        
        public selectjichayuanRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectjichayuanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectjichayuanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectjichayuanResult;
        
        public selectjichayuanResponse() {
        }
        
        public selectjichayuanResponse(System.Data.DataSet selectjichayuanResult) {
            this.selectjichayuanResult = selectjichayuanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectcheshudanwei", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectcheshudanweiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int VehicleID;
        
        public selectcheshudanweiRequest() {
        }
        
        public selectcheshudanweiRequest(int VehicleID) {
            this.VehicleID = VehicleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectcheshudanweiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectcheshudanweiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectcheshudanweiResult;
        
        public selectcheshudanweiResponse() {
        }
        
        public selectcheshudanweiResponse(System.Data.DataSet selectcheshudanweiResult) {
            this.selectcheshudanweiResult = selectcheshudanweiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectjichaxianmu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectjichaxianmuRequest {
        
        public selectjichaxianmuRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectjichaxianmuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectjichaxianmuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectjichaxianmuResult;
        
        public selectjichaxianmuResponse() {
        }
        
        public selectjichaxianmuResponse(System.Data.DataSet selectjichaxianmuResult) {
            this.selectjichaxianmuResult = selectjichaxianmuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectjichaxiangmu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectjichaxiangmuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int TheStationInspectionID;
        
        public selectjichaxiangmuRequest() {
        }
        
        public selectjichaxiangmuRequest(int TheStationInspectionID) {
            this.TheStationInspectionID = TheStationInspectionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectjichaxiangmuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectjichaxiangmuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectjichaxiangmuResult;
        
        public selectjichaxiangmuResponse() {
        }
        
        public selectjichaxiangmuResponse(System.Data.DataSet selectjichaxiangmuResult) {
            this.selectjichaxiangmuResult = selectjichaxiangmuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SELECTJICHAXIANGMUMINGXI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SELECTJICHAXIANGMUMINGXIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PlateNumber;
        
        public SELECTJICHAXIANGMUMINGXIRequest() {
        }
        
        public SELECTJICHAXIANGMUMINGXIRequest(string PlateNumber) {
            this.PlateNumber = PlateNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SELECTJICHAXIANGMUMINGXIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SELECTJICHAXIANGMUMINGXIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SELECTJICHAXIANGMUMINGXIResult;
        
        public SELECTJICHAXIANGMUMINGXIResponse() {
        }
        
        public SELECTJICHAXIANGMUMINGXIResponse(System.Data.DataSet SELECTJICHAXIANGMUMINGXIResult) {
            this.SELECTJICHAXIANGMUMINGXIResult = SELECTJICHAXIANGMUMINGXIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectcheliangjichadan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectcheliangjichadanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VehiclePaiNumber;
        
        public selectcheliangjichadanRequest() {
        }
        
        public selectcheliangjichadanRequest(string VehiclePaiNumber) {
            this.VehiclePaiNumber = VehiclePaiNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectcheliangjichadanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectcheliangjichadanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectcheliangjichadanResult;
        
        public selectcheliangjichadanResponse() {
        }
        
        public selectcheliangjichadanResponse(System.Data.DataSet selectcheliangjichadanResult) {
            this.selectcheliangjichadanResult = selectcheliangjichadanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface chezhanjichaChannel : 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class chezhanjichaClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha>, 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha {
        
        public chezhanjichaClient() {
        }
        
        public chezhanjichaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public chezhanjichaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public chezhanjichaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public chezhanjichaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.Selectchelaing(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingRequest request) {
            return base.Channel.Selectchelaing(request);
        }
        
        public System.Data.DataSet Selectchelaing() {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingRequest();
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).Selectchelaing(inValue);
            return retVal.SelectchelaingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.SelectchelaingAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingRequest request) {
            return base.Channel.SelectchelaingAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingResponse> SelectchelaingAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).SelectchelaingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.SelectchelaingID(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDRequest request) {
            return base.Channel.SelectchelaingID(request);
        }
        
        public System.Data.DataSet SelectchelaingID(string PlateNumber) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDRequest();
            inValue.PlateNumber = PlateNumber;
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).SelectchelaingID(inValue);
            return retVal.SelectchelaingIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.SelectchelaingIDAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDRequest request) {
            return base.Channel.SelectchelaingIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDResponse> SelectchelaingIDAsync(string PlateNumber) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingIDRequest();
            inValue.PlateNumber = PlateNumber;
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).SelectchelaingIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.Selectchelaingxinhao(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoRequest request) {
            return base.Channel.Selectchelaingxinhao(request);
        }
        
        public System.Data.DataSet Selectchelaingxinhao(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoRequest();
            inValue.VehicleID = VehicleID;
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).Selectchelaingxinhao(inValue);
            return retVal.SelectchelaingxinhaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.SelectchelaingxinhaoAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoRequest request) {
            return base.Channel.SelectchelaingxinhaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoResponse> SelectchelaingxinhaoAsync(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SelectchelaingxinhaoRequest();
            inValue.VehicleID = VehicleID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).SelectchelaingxinhaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectbanci(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciRequest request) {
            return base.Channel.selectbanci(request);
        }
        
        public System.Data.DataSet selectbanci() {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciRequest();
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectbanci(inValue);
            return retVal.selectbanciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectbanciAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciRequest request) {
            return base.Channel.selectbanciAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciResponse> selectbanciAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbanciRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectbanciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectbancirenshu(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuRequest request) {
            return base.Channel.selectbancirenshu(request);
        }
        
        public System.Data.DataSet selectbancirenshu(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuRequest();
            inValue.VehicleID = VehicleID;
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectbancirenshu(inValue);
            return retVal.selectbancirenshuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectbancirenshuAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuRequest request) {
            return base.Channel.selectbancirenshuAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuResponse> selectbancirenshuAsync(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuRequest();
            inValue.VehicleID = VehicleID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectbancirenshuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectbancirenshuertongshu(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuRequest request) {
            return base.Channel.selectbancirenshuertongshu(request);
        }
        
        public System.Data.DataSet selectbancirenshuertongshu(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuRequest();
            inValue.VehicleID = VehicleID;
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectbancirenshuertongshu(inValue);
            return retVal.selectbancirenshuertongshuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectbancirenshuertongshuAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuRequest request) {
            return base.Channel.selectbancirenshuertongshuAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuResponse> selectbancirenshuertongshuAsync(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectbancirenshuertongshuRequest();
            inValue.VehicleID = VehicleID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectbancirenshuertongshuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.INSERTchuzhanxinxi(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiRequest request) {
            return base.Channel.INSERTchuzhanxinxi(request);
        }
        
        public int INSERTchuzhanxinxi(int VehicleID, int CarBelongToTheUnitID, int UserID, int CreateUserID, int DeleteUserID, int TheNumberOfPassengers, int ChildrenFree, string ComprehensiveResults, bool AllPass, System.DateTime CreateTime) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiRequest();
            inValue.VehicleID = VehicleID;
            inValue.CarBelongToTheUnitID = CarBelongToTheUnitID;
            inValue.UserID = UserID;
            inValue.CreateUserID = CreateUserID;
            inValue.DeleteUserID = DeleteUserID;
            inValue.TheNumberOfPassengers = TheNumberOfPassengers;
            inValue.ChildrenFree = ChildrenFree;
            inValue.ComprehensiveResults = ComprehensiveResults;
            inValue.AllPass = AllPass;
            inValue.CreateTime = CreateTime;
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).INSERTchuzhanxinxi(inValue);
            return retVal.INSERTchuzhanxinxiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.INSERTchuzhanxinxiAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiRequest request) {
            return base.Channel.INSERTchuzhanxinxiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiResponse> INSERTchuzhanxinxiAsync(int VehicleID, int CarBelongToTheUnitID, int UserID, int CreateUserID, int DeleteUserID, int TheNumberOfPassengers, int ChildrenFree, string ComprehensiveResults, bool AllPass, System.DateTime CreateTime) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.INSERTchuzhanxinxiRequest();
            inValue.VehicleID = VehicleID;
            inValue.CarBelongToTheUnitID = CarBelongToTheUnitID;
            inValue.UserID = UserID;
            inValue.CreateUserID = CreateUserID;
            inValue.DeleteUserID = DeleteUserID;
            inValue.TheNumberOfPassengers = TheNumberOfPassengers;
            inValue.ChildrenFree = ChildrenFree;
            inValue.ComprehensiveResults = ComprehensiveResults;
            inValue.AllPass = AllPass;
            inValue.CreateTime = CreateTime;
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).INSERTchuzhanxinxiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectjichayuan(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanRequest request) {
            return base.Channel.selectjichayuan(request);
        }
        
        public System.Data.DataSet selectjichayuan() {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanRequest();
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectjichayuan(inValue);
            return retVal.selectjichayuanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectjichayuanAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanRequest request) {
            return base.Channel.selectjichayuanAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanResponse> selectjichayuanAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichayuanRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectjichayuanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectcheshudanwei(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiRequest request) {
            return base.Channel.selectcheshudanwei(request);
        }
        
        public System.Data.DataSet selectcheshudanwei(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiRequest();
            inValue.VehicleID = VehicleID;
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectcheshudanwei(inValue);
            return retVal.selectcheshudanweiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectcheshudanweiAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiRequest request) {
            return base.Channel.selectcheshudanweiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiResponse> selectcheshudanweiAsync(int VehicleID) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheshudanweiRequest();
            inValue.VehicleID = VehicleID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectcheshudanweiAsync(inValue);
        }
        
        public int insectchuzhanmingxi(int TheStationInspectionID, int CreateUserID, int DeleteUserID, int AuditByComparisonNaneID, bool YON, System.DateTime CreateTime) {
            return base.Channel.insectchuzhanmingxi(TheStationInspectionID, CreateUserID, DeleteUserID, AuditByComparisonNaneID, YON, CreateTime);
        }
        
        public System.Threading.Tasks.Task<int> insectchuzhanmingxiAsync(int TheStationInspectionID, int CreateUserID, int DeleteUserID, int AuditByComparisonNaneID, bool YON, System.DateTime CreateTime) {
            return base.Channel.insectchuzhanmingxiAsync(TheStationInspectionID, CreateUserID, DeleteUserID, AuditByComparisonNaneID, YON, CreateTime);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectjichaxianmu(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuRequest request) {
            return base.Channel.selectjichaxianmu(request);
        }
        
        public System.Data.DataSet selectjichaxianmu() {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuRequest();
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectjichaxianmu(inValue);
            return retVal.selectjichaxianmuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectjichaxianmuAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuRequest request) {
            return base.Channel.selectjichaxianmuAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuResponse> selectjichaxianmuAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxianmuRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectjichaxianmuAsync(inValue);
        }
        
        public int updatechelaingzhuangtai(int VehicleID) {
            return base.Channel.updatechelaingzhuangtai(VehicleID);
        }
        
        public System.Threading.Tasks.Task<int> updatechelaingzhuangtaiAsync(int VehicleID) {
            return base.Channel.updatechelaingzhuangtaiAsync(VehicleID);
        }
        
        public int updatechelaingzhuangtaizuowei(int VehicleID) {
            return base.Channel.updatechelaingzhuangtaizuowei(VehicleID);
        }
        
        public System.Threading.Tasks.Task<int> updatechelaingzhuangtaizuoweiAsync(int VehicleID) {
            return base.Channel.updatechelaingzhuangtaizuoweiAsync(VehicleID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectjichaxiangmu(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuRequest request) {
            return base.Channel.selectjichaxiangmu(request);
        }
        
        public System.Data.DataSet selectjichaxiangmu(int TheStationInspectionID) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuRequest();
            inValue.TheStationInspectionID = TheStationInspectionID;
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectjichaxiangmu(inValue);
            return retVal.selectjichaxiangmuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectjichaxiangmuAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuRequest request) {
            return base.Channel.selectjichaxiangmuAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuResponse> selectjichaxiangmuAsync(int TheStationInspectionID) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectjichaxiangmuRequest();
            inValue.TheStationInspectionID = TheStationInspectionID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectjichaxiangmuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXI(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIRequest request) {
            return base.Channel.SELECTJICHAXIANGMUMINGXI(request);
        }
        
        public System.Data.DataSet SELECTJICHAXIANGMUMINGXI(string PlateNumber) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIRequest();
            inValue.PlateNumber = PlateNumber;
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).SELECTJICHAXIANGMUMINGXI(inValue);
            return retVal.SELECTJICHAXIANGMUMINGXIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIRequest request) {
            return base.Channel.SELECTJICHAXIANGMUMINGXIAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIResponse> SELECTJICHAXIANGMUMINGXIAsync(string PlateNumber) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.SELECTJICHAXIANGMUMINGXIRequest();
            inValue.PlateNumber = PlateNumber;
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).SELECTJICHAXIANGMUMINGXIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanResponse 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectcheliangjichadan(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanRequest request) {
            return base.Channel.selectcheliangjichadan(request);
        }
        
        public System.Data.DataSet selectcheliangjichadan(string VehiclePaiNumber) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanRequest();
            inValue.VehiclePaiNumber = VehiclePaiNumber;
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectcheliangjichadan(inValue);
            return retVal.selectcheliangjichadanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanResponse> 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha.selectcheliangjichadanAsync(集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanRequest request) {
            return base.Channel.selectcheliangjichadanAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanResponse> selectcheliangjichadanAsync(string VehiclePaiNumber) {
            集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.selectcheliangjichadanRequest();
            inValue.VehiclePaiNumber = VehiclePaiNumber;
            return ((集团客运综合管理系统.BLL集团客运综合管理.chuzhanjicha.chezhanjicha.chezhanjicha)(this)).selectcheliangjichadanAsync(inValue);
        }
    }
}
