//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease")]
    public interface TicketSease {
        
        // CODEGEN: 参数“SelectchepiaoResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Selectchepiao", ReplyAction="http://tempuri.org/TicketSease/SelectchepiaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoResponse Selectchepiao(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Selectchepiao", ReplyAction="http://tempuri.org/TicketSease/SelectchepiaoResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoResponse> SelectchepiaoAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoRequest request);
        
        // CODEGEN: 参数“SelectbancionshijianResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Selectbancionshijian", ReplyAction="http://tempuri.org/TicketSease/SelectbancionshijianResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianResponse Selectbancionshijian(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Selectbancionshijian", ReplyAction="http://tempuri.org/TicketSease/SelectbancionshijianResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianResponse> SelectbancionshijianAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianRequest request);
        
        // CODEGEN: 参数“SelectczhandianandpiaojiaResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Selectczhandianandpiaojia", ReplyAction="http://tempuri.org/TicketSease/SelectczhandianandpiaojiaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaResponse Selectczhandianandpiaojia(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Selectczhandianandpiaojia", ReplyAction="http://tempuri.org/TicketSease/SelectczhandianandpiaojiaResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaResponse> SelectczhandianandpiaojiaAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaRequest request);
        
        // CODEGEN: 参数“SelectStaionResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/SelectStaion", ReplyAction="http://tempuri.org/TicketSease/SelectStaionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionResponse SelectStaion(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/SelectStaion", ReplyAction="http://tempuri.org/TicketSease/SelectStaionResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionResponse> SelectStaionAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionRequest request);
        
        // CODEGEN: 参数“SelelctticketzhuangtaiResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Selelctticketzhuangtai", ReplyAction="http://tempuri.org/TicketSease/SelelctticketzhuangtaiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiResponse Selelctticketzhuangtai(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Selelctticketzhuangtai", ReplyAction="http://tempuri.org/TicketSease/SelelctticketzhuangtaiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiResponse> SelelctticketzhuangtaiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiRequest request);
        
        // CODEGEN: 参数“selectchelaingdexiweiResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectchelaingdexiwei", ReplyAction="http://tempuri.org/TicketSease/selectchelaingdexiweiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiResponse selectchelaingdexiwei(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectchelaingdexiwei", ReplyAction="http://tempuri.org/TicketSease/selectchelaingdexiweiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiResponse> selectchelaingdexiweiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Updatexiweizhaungtai", ReplyAction="http://tempuri.org/TicketSease/UpdatexiweizhaungtaiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Updatexiweizhaungtai(int SeatsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Updatexiweizhaungtai", ReplyAction="http://tempuri.org/TicketSease/UpdatexiweizhaungtaiResponse")]
        System.Threading.Tasks.Task<int> UpdatexiweizhaungtaiAsync(int SeatsID);
        
        // CODEGEN: 参数“TicketMark”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Insectdingpiaoxinxi", ReplyAction="http://tempuri.org/TicketSease/InsectdingpiaoxinxiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiResponse Insectdingpiaoxinxi(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Insectdingpiaoxinxi", ReplyAction="http://tempuri.org/TicketSease/InsectdingpiaoxinxiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiResponse> InsectdingpiaoxinxiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiRequest request);
        
        // CODEGEN: 参数“SelectzuidapiohaoResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Selectzuidapiohao", ReplyAction="http://tempuri.org/TicketSease/SelectzuidapiohaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoResponse Selectzuidapiohao(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Selectzuidapiohao", ReplyAction="http://tempuri.org/TicketSease/SelectzuidapiohaoResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoResponse> SelectzuidapiohaoAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/DELETETicketingInformation", ReplyAction="http://tempuri.org/TicketSease/DELETETicketingInformationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DELETETicketingInformation(int TicketingInformationID, int TicketPriceTypeID, int TicketStateID, int Tuipiaoshouxufei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/DELETETicketingInformation", ReplyAction="http://tempuri.org/TicketSease/DELETETicketingInformationResponse")]
        System.Threading.Tasks.Task<int> DELETETicketingInformationAsync(int TicketingInformationID, int TicketPriceTypeID, int TicketStateID, int Tuipiaoshouxufei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/DELETETicketingInformationtuipiao", ReplyAction="http://tempuri.org/TicketSease/DELETETicketingInformationtuipiaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DELETETicketingInformationtuipiao(int TicketingInformationID, int TicketPriceTypeID, int Tuipiaoshouxufei, int TicketStateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/DELETETicketingInformationtuipiao", ReplyAction="http://tempuri.org/TicketSease/DELETETicketingInformationtuipiaoResponse")]
        System.Threading.Tasks.Task<int> DELETETicketingInformationtuipiaoAsync(int TicketingInformationID, int TicketPriceTypeID, int Tuipiaoshouxufei, int TicketStateID);
        
        // CODEGEN: 参数“SelectpiaojiaIDResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/SelectpiaojiaID", ReplyAction="http://tempuri.org/TicketSease/SelectpiaojiaIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDResponse SelectpiaojiaID(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/SelectpiaojiaID", ReplyAction="http://tempuri.org/TicketSease/SelectpiaojiaIDResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDResponse> SelectpiaojiaIDAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Updatexiweizhaungtaiweibaofei", ReplyAction="http://tempuri.org/TicketSease/UpdatexiweizhaungtaiweibaofeiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Updatexiweizhaungtaiweibaofei(int SeatsID, int SeatsStateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/Updatexiweizhaungtaiweibaofei", ReplyAction="http://tempuri.org/TicketSease/UpdatexiweizhaungtaiweibaofeiResponse")]
        System.Threading.Tasks.Task<int> UpdatexiweizhaungtaiweibaofeiAsync(int SeatsID, int SeatsStateID);
        
        // CODEGEN: 参数“MoHuSelectpiaoxinxiResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/MoHuSelectpiaoxinxi", ReplyAction="http://tempuri.org/TicketSease/MoHuSelectpiaoxinxiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiResponse MoHuSelectpiaoxinxi(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/MoHuSelectpiaoxinxi", ReplyAction="http://tempuri.org/TicketSease/MoHuSelectpiaoxinxiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiResponse> MoHuSelectpiaoxinxiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiRequest request);
        
        // CODEGEN: 参数“selectchexingResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectchexing", ReplyAction="http://tempuri.org/TicketSease/selectchexingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingResponse selectchexing(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectchexing", ReplyAction="http://tempuri.org/TicketSease/selectchexingResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingResponse> selectchexingAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingRequest request);
        
        // CODEGEN: 参数“selectpiaoxingResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectpiaoxing", ReplyAction="http://tempuri.org/TicketSease/selectpiaoxingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingResponse selectpiaoxing(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectpiaoxing", ReplyAction="http://tempuri.org/TicketSease/selectpiaoxingResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingResponse> selectpiaoxingAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingRequest request);
        
        // CODEGEN: 参数“selectpiaozhaungrtaiResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectpiaozhaungrtai", ReplyAction="http://tempuri.org/TicketSease/selectpiaozhaungrtaiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiResponse selectpiaozhaungrtai(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectpiaozhaungrtai", ReplyAction="http://tempuri.org/TicketSease/selectpiaozhaungrtaiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiResponse> selectpiaozhaungrtaiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiRequest request);
        
        // CODEGEN: 参数“selectfeipiaoxinxiResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectfeipiaoxinxi", ReplyAction="http://tempuri.org/TicketSease/selectfeipiaoxinxiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiResponse selectfeipiaoxinxi(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectfeipiaoxinxi", ReplyAction="http://tempuri.org/TicketSease/selectfeipiaoxinxiResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiResponse> selectfeipiaoxinxiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiRequest request);
        
        // CODEGEN: 参数“selectgenjuyonghuIDResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectgenjuyonghuID", ReplyAction="http://tempuri.org/TicketSease/selectgenjuyonghuIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDResponse selectgenjuyonghuID(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectgenjuyonghuID", ReplyAction="http://tempuri.org/TicketSease/selectgenjuyonghuIDResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDResponse> selectgenjuyonghuIDAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/UPDATEdangqianpiaohao", ReplyAction="http://tempuri.org/TicketSease/UPDATEdangqianpiaohaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UPDATEdangqianpiaohao(int CurrentTicketMark, int SurplusQuantity, int ReceiveUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/UPDATEdangqianpiaohao", ReplyAction="http://tempuri.org/TicketSease/UPDATEdangqianpiaohaoResponse")]
        System.Threading.Tasks.Task<int> UPDATEdangqianpiaohaoAsync(int CurrentTicketMark, int SurplusQuantity, int ReceiveUserID);
        
        // CODEGEN: 参数“selectyanzhengmaResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectyanzhengma", ReplyAction="http://tempuri.org/TicketSease/selectyanzhengmaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaResponse selectyanzhengma(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/selectyanzhengma", ReplyAction="http://tempuri.org/TicketSease/selectyanzhengmaResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaResponse> selectyanzhengmaAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaRequest request);
        
        // CODEGEN: 参数“DingPiaoYanZhengMa”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/updateyanzhengma", ReplyAction="http://tempuri.org/TicketSease/updateyanzhengmaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaResponse updateyanzhengma(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TicketSease/updateyanzhengma", ReplyAction="http://tempuri.org/TicketSease/updateyanzhengmaResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaResponse> updateyanzhengmaAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Selectchepiao", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectchepiaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int StartingStationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int TerminalStationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int TicketPriceTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string 给出时间;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int FrequencyID;
        
        public SelectchepiaoRequest() {
        }
        
        public SelectchepiaoRequest(int StartingStationID, int TerminalStationID, int TicketPriceTypeID, string 给出时间, int FrequencyID) {
            this.StartingStationID = StartingStationID;
            this.TerminalStationID = TerminalStationID;
            this.TicketPriceTypeID = TicketPriceTypeID;
            this.给出时间 = 给出时间;
            this.FrequencyID = FrequencyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectchepiaoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectchepiaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectchepiaoResult;
        
        public SelectchepiaoResponse() {
        }
        
        public SelectchepiaoResponse(System.Data.DataSet SelectchepiaoResult) {
            this.SelectchepiaoResult = SelectchepiaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Selectbancionshijian", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectbancionshijianRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int StartingStationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int TerminalStationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int TicketPriceTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string 给出时间;
        
        public SelectbancionshijianRequest() {
        }
        
        public SelectbancionshijianRequest(int StartingStationID, int TerminalStationID, int TicketPriceTypeID, string 给出时间) {
            this.StartingStationID = StartingStationID;
            this.TerminalStationID = TerminalStationID;
            this.TicketPriceTypeID = TicketPriceTypeID;
            this.给出时间 = 给出时间;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectbancionshijianResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectbancionshijianResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectbancionshijianResult;
        
        public SelectbancionshijianResponse() {
        }
        
        public SelectbancionshijianResponse(System.Data.DataSet SelectbancionshijianResult) {
            this.SelectbancionshijianResult = SelectbancionshijianResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Selectczhandianandpiaojia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectczhandianandpiaojiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int StartingStationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int TerminalStationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int TicketPriceTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int FrequencyID;
        
        public SelectczhandianandpiaojiaRequest() {
        }
        
        public SelectczhandianandpiaojiaRequest(int StartingStationID, int TerminalStationID, int TicketPriceTypeID, int FrequencyID) {
            this.StartingStationID = StartingStationID;
            this.TerminalStationID = TerminalStationID;
            this.TicketPriceTypeID = TicketPriceTypeID;
            this.FrequencyID = FrequencyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectczhandianandpiaojiaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectczhandianandpiaojiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectczhandianandpiaojiaResult;
        
        public SelectczhandianandpiaojiaResponse() {
        }
        
        public SelectczhandianandpiaojiaResponse(System.Data.DataSet SelectczhandianandpiaojiaResult) {
            this.SelectczhandianandpiaojiaResult = SelectczhandianandpiaojiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectStaion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectStaionRequest {
        
        public SelectStaionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectStaionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectStaionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectStaionResult;
        
        public SelectStaionResponse() {
        }
        
        public SelectStaionResponse(System.Data.DataSet SelectStaionResult) {
            this.SelectStaionResult = SelectStaionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Selelctticketzhuangtai", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelelctticketzhuangtaiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int FrequencyID;
        
        public SelelctticketzhuangtaiRequest() {
        }
        
        public SelelctticketzhuangtaiRequest(int FrequencyID) {
            this.FrequencyID = FrequencyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelelctticketzhuangtaiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelelctticketzhuangtaiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelelctticketzhuangtaiResult;
        
        public SelelctticketzhuangtaiResponse() {
        }
        
        public SelelctticketzhuangtaiResponse(System.Data.DataSet SelelctticketzhuangtaiResult) {
            this.SelelctticketzhuangtaiResult = SelelctticketzhuangtaiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectchelaingdexiwei", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectchelaingdexiweiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int FrequencyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int 个数;
        
        public selectchelaingdexiweiRequest() {
        }
        
        public selectchelaingdexiweiRequest(int FrequencyID, int 个数) {
            this.FrequencyID = FrequencyID;
            this.个数 = 个数;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectchelaingdexiweiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectchelaingdexiweiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectchelaingdexiweiResult;
        
        public selectchelaingdexiweiResponse() {
        }
        
        public selectchelaingdexiweiResponse(System.Data.DataSet selectchelaingdexiweiResult) {
            this.selectchelaingdexiweiResult = selectchelaingdexiweiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insectdingpiaoxinxi", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsectdingpiaoxinxiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int FrequencyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int SeatsID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int CreateUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int DeleteUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TicketMark;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.DateTime TicketingDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public System.DateTime TicketingDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public System.DateTime CreateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public int TicketPriceTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public decimal Howmoney;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public int TicketStateID;
        
        public InsectdingpiaoxinxiRequest() {
        }
        
        public InsectdingpiaoxinxiRequest(int FrequencyID, int SeatsID, int CreateUserID, int DeleteUserID, string TicketMark, System.DateTime TicketingDate, System.DateTime TicketingDateTime, System.DateTime CreateTime, int TicketPriceTypeID, decimal Howmoney, int TicketStateID) {
            this.FrequencyID = FrequencyID;
            this.SeatsID = SeatsID;
            this.CreateUserID = CreateUserID;
            this.DeleteUserID = DeleteUserID;
            this.TicketMark = TicketMark;
            this.TicketingDate = TicketingDate;
            this.TicketingDateTime = TicketingDateTime;
            this.CreateTime = CreateTime;
            this.TicketPriceTypeID = TicketPriceTypeID;
            this.Howmoney = Howmoney;
            this.TicketStateID = TicketStateID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsectdingpiaoxinxiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsectdingpiaoxinxiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int InsectdingpiaoxinxiResult;
        
        public InsectdingpiaoxinxiResponse() {
        }
        
        public InsectdingpiaoxinxiResponse(int InsectdingpiaoxinxiResult) {
            this.InsectdingpiaoxinxiResult = InsectdingpiaoxinxiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Selectzuidapiohao", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectzuidapiohaoRequest {
        
        public SelectzuidapiohaoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectzuidapiohaoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectzuidapiohaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectzuidapiohaoResult;
        
        public SelectzuidapiohaoResponse() {
        }
        
        public SelectzuidapiohaoResponse(System.Data.DataSet SelectzuidapiohaoResult) {
            this.SelectzuidapiohaoResult = SelectzuidapiohaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectpiaojiaID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectpiaojiaIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SeatsID;
        
        public SelectpiaojiaIDRequest() {
        }
        
        public SelectpiaojiaIDRequest(int SeatsID) {
            this.SeatsID = SeatsID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectpiaojiaIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectpiaojiaIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet SelectpiaojiaIDResult;
        
        public SelectpiaojiaIDResponse() {
        }
        
        public SelectpiaojiaIDResponse(System.Data.DataSet SelectpiaojiaIDResult) {
            this.SelectpiaojiaIDResult = SelectpiaojiaIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoHuSelectpiaoxinxi", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MoHuSelectpiaoxinxiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string 动态条件;
        
        public MoHuSelectpiaoxinxiRequest() {
        }
        
        public MoHuSelectpiaoxinxiRequest(string 动态条件) {
            this.动态条件 = 动态条件;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoHuSelectpiaoxinxiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MoHuSelectpiaoxinxiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet MoHuSelectpiaoxinxiResult;
        
        public MoHuSelectpiaoxinxiResponse() {
        }
        
        public MoHuSelectpiaoxinxiResponse(System.Data.DataSet MoHuSelectpiaoxinxiResult) {
            this.MoHuSelectpiaoxinxiResult = MoHuSelectpiaoxinxiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectchexing", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectchexingRequest {
        
        public selectchexingRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectchexingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectchexingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectchexingResult;
        
        public selectchexingResponse() {
        }
        
        public selectchexingResponse(System.Data.DataSet selectchexingResult) {
            this.selectchexingResult = selectchexingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectpiaoxing", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectpiaoxingRequest {
        
        public selectpiaoxingRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectpiaoxingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectpiaoxingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectpiaoxingResult;
        
        public selectpiaoxingResponse() {
        }
        
        public selectpiaoxingResponse(System.Data.DataSet selectpiaoxingResult) {
            this.selectpiaoxingResult = selectpiaoxingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectpiaozhaungrtai", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectpiaozhaungrtaiRequest {
        
        public selectpiaozhaungrtaiRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectpiaozhaungrtaiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectpiaozhaungrtaiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectpiaozhaungrtaiResult;
        
        public selectpiaozhaungrtaiResponse() {
        }
        
        public selectpiaozhaungrtaiResponse(System.Data.DataSet selectpiaozhaungrtaiResult) {
            this.selectpiaozhaungrtaiResult = selectpiaozhaungrtaiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectfeipiaoxinxi", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectfeipiaoxinxiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SeatsID;
        
        public selectfeipiaoxinxiRequest() {
        }
        
        public selectfeipiaoxinxiRequest(int SeatsID) {
            this.SeatsID = SeatsID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectfeipiaoxinxiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectfeipiaoxinxiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectfeipiaoxinxiResult;
        
        public selectfeipiaoxinxiResponse() {
        }
        
        public selectfeipiaoxinxiResponse(System.Data.DataSet selectfeipiaoxinxiResult) {
            this.selectfeipiaoxinxiResult = selectfeipiaoxinxiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectgenjuyonghuID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectgenjuyonghuIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserID;
        
        public selectgenjuyonghuIDRequest() {
        }
        
        public selectgenjuyonghuIDRequest(int UserID) {
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectgenjuyonghuIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectgenjuyonghuIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectgenjuyonghuIDResult;
        
        public selectgenjuyonghuIDResponse() {
        }
        
        public selectgenjuyonghuIDResponse(System.Data.DataSet selectgenjuyonghuIDResult) {
            this.selectgenjuyonghuIDResult = selectgenjuyonghuIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectyanzhengma", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectyanzhengmaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DingPiaoYanZhengMa;
        
        public selectyanzhengmaRequest() {
        }
        
        public selectyanzhengmaRequest(string DingPiaoYanZhengMa) {
            this.DingPiaoYanZhengMa = DingPiaoYanZhengMa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectyanzhengmaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectyanzhengmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectyanzhengmaResult;
        
        public selectyanzhengmaResponse() {
        }
        
        public selectyanzhengmaResponse(System.Data.DataSet selectyanzhengmaResult) {
            this.selectyanzhengmaResult = selectyanzhengmaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateyanzhengma", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updateyanzhengmaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ShiFou;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DingPiaoYanZhengMa;
        
        public updateyanzhengmaRequest() {
        }
        
        public updateyanzhengmaRequest(bool ShiFou, string DingPiaoYanZhengMa) {
            this.ShiFou = ShiFou;
            this.DingPiaoYanZhengMa = DingPiaoYanZhengMa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateyanzhengmaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updateyanzhengmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int updateyanzhengmaResult;
        
        public updateyanzhengmaResponse() {
        }
        
        public updateyanzhengmaResponse(int updateyanzhengmaResult) {
            this.updateyanzhengmaResult = updateyanzhengmaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TicketSeaseChannel : 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicketSeaseClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease>, 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease {
        
        public TicketSeaseClient() {
        }
        
        public TicketSeaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TicketSeaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketSeaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketSeaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.Selectchepiao(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoRequest request) {
            return base.Channel.Selectchepiao(request);
        }
        
        public System.Data.DataSet Selectchepiao(int StartingStationID, int TerminalStationID, int TicketPriceTypeID, string 给出时间, int FrequencyID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoRequest();
            inValue.StartingStationID = StartingStationID;
            inValue.TerminalStationID = TerminalStationID;
            inValue.TicketPriceTypeID = TicketPriceTypeID;
            inValue.给出时间 = 给出时间;
            inValue.FrequencyID = FrequencyID;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).Selectchepiao(inValue);
            return retVal.SelectchepiaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.SelectchepiaoAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoRequest request) {
            return base.Channel.SelectchepiaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoResponse> SelectchepiaoAsync(int StartingStationID, int TerminalStationID, int TicketPriceTypeID, string 给出时间, int FrequencyID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectchepiaoRequest();
            inValue.StartingStationID = StartingStationID;
            inValue.TerminalStationID = TerminalStationID;
            inValue.TicketPriceTypeID = TicketPriceTypeID;
            inValue.给出时间 = 给出时间;
            inValue.FrequencyID = FrequencyID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).SelectchepiaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.Selectbancionshijian(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianRequest request) {
            return base.Channel.Selectbancionshijian(request);
        }
        
        public System.Data.DataSet Selectbancionshijian(int StartingStationID, int TerminalStationID, int TicketPriceTypeID, string 给出时间) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianRequest();
            inValue.StartingStationID = StartingStationID;
            inValue.TerminalStationID = TerminalStationID;
            inValue.TicketPriceTypeID = TicketPriceTypeID;
            inValue.给出时间 = 给出时间;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).Selectbancionshijian(inValue);
            return retVal.SelectbancionshijianResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.SelectbancionshijianAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianRequest request) {
            return base.Channel.SelectbancionshijianAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianResponse> SelectbancionshijianAsync(int StartingStationID, int TerminalStationID, int TicketPriceTypeID, string 给出时间) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectbancionshijianRequest();
            inValue.StartingStationID = StartingStationID;
            inValue.TerminalStationID = TerminalStationID;
            inValue.TicketPriceTypeID = TicketPriceTypeID;
            inValue.给出时间 = 给出时间;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).SelectbancionshijianAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.Selectczhandianandpiaojia(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaRequest request) {
            return base.Channel.Selectczhandianandpiaojia(request);
        }
        
        public System.Data.DataSet Selectczhandianandpiaojia(int StartingStationID, int TerminalStationID, int TicketPriceTypeID, int FrequencyID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaRequest();
            inValue.StartingStationID = StartingStationID;
            inValue.TerminalStationID = TerminalStationID;
            inValue.TicketPriceTypeID = TicketPriceTypeID;
            inValue.FrequencyID = FrequencyID;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).Selectczhandianandpiaojia(inValue);
            return retVal.SelectczhandianandpiaojiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.SelectczhandianandpiaojiaAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaRequest request) {
            return base.Channel.SelectczhandianandpiaojiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaResponse> SelectczhandianandpiaojiaAsync(int StartingStationID, int TerminalStationID, int TicketPriceTypeID, int FrequencyID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectczhandianandpiaojiaRequest();
            inValue.StartingStationID = StartingStationID;
            inValue.TerminalStationID = TerminalStationID;
            inValue.TicketPriceTypeID = TicketPriceTypeID;
            inValue.FrequencyID = FrequencyID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).SelectczhandianandpiaojiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.SelectStaion(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionRequest request) {
            return base.Channel.SelectStaion(request);
        }
        
        public System.Data.DataSet SelectStaion() {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionRequest();
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).SelectStaion(inValue);
            return retVal.SelectStaionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.SelectStaionAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionRequest request) {
            return base.Channel.SelectStaionAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionResponse> SelectStaionAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectStaionRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).SelectStaionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.Selelctticketzhuangtai(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiRequest request) {
            return base.Channel.Selelctticketzhuangtai(request);
        }
        
        public System.Data.DataSet Selelctticketzhuangtai(int FrequencyID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiRequest();
            inValue.FrequencyID = FrequencyID;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).Selelctticketzhuangtai(inValue);
            return retVal.SelelctticketzhuangtaiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.SelelctticketzhuangtaiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiRequest request) {
            return base.Channel.SelelctticketzhuangtaiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiResponse> SelelctticketzhuangtaiAsync(int FrequencyID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelelctticketzhuangtaiRequest();
            inValue.FrequencyID = FrequencyID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).SelelctticketzhuangtaiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectchelaingdexiwei(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiRequest request) {
            return base.Channel.selectchelaingdexiwei(request);
        }
        
        public System.Data.DataSet selectchelaingdexiwei(int FrequencyID, int 个数) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiRequest();
            inValue.FrequencyID = FrequencyID;
            inValue.个数 = 个数;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectchelaingdexiwei(inValue);
            return retVal.selectchelaingdexiweiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectchelaingdexiweiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiRequest request) {
            return base.Channel.selectchelaingdexiweiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiResponse> selectchelaingdexiweiAsync(int FrequencyID, int 个数) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchelaingdexiweiRequest();
            inValue.FrequencyID = FrequencyID;
            inValue.个数 = 个数;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectchelaingdexiweiAsync(inValue);
        }
        
        public int Updatexiweizhaungtai(int SeatsID) {
            return base.Channel.Updatexiweizhaungtai(SeatsID);
        }
        
        public System.Threading.Tasks.Task<int> UpdatexiweizhaungtaiAsync(int SeatsID) {
            return base.Channel.UpdatexiweizhaungtaiAsync(SeatsID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.Insectdingpiaoxinxi(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiRequest request) {
            return base.Channel.Insectdingpiaoxinxi(request);
        }
        
        public int Insectdingpiaoxinxi(int FrequencyID, int SeatsID, int CreateUserID, int DeleteUserID, string TicketMark, System.DateTime TicketingDate, System.DateTime TicketingDateTime, System.DateTime CreateTime, int TicketPriceTypeID, decimal Howmoney, int TicketStateID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiRequest();
            inValue.FrequencyID = FrequencyID;
            inValue.SeatsID = SeatsID;
            inValue.CreateUserID = CreateUserID;
            inValue.DeleteUserID = DeleteUserID;
            inValue.TicketMark = TicketMark;
            inValue.TicketingDate = TicketingDate;
            inValue.TicketingDateTime = TicketingDateTime;
            inValue.CreateTime = CreateTime;
            inValue.TicketPriceTypeID = TicketPriceTypeID;
            inValue.Howmoney = Howmoney;
            inValue.TicketStateID = TicketStateID;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).Insectdingpiaoxinxi(inValue);
            return retVal.InsectdingpiaoxinxiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.InsectdingpiaoxinxiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiRequest request) {
            return base.Channel.InsectdingpiaoxinxiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiResponse> InsectdingpiaoxinxiAsync(int FrequencyID, int SeatsID, int CreateUserID, int DeleteUserID, string TicketMark, System.DateTime TicketingDate, System.DateTime TicketingDateTime, System.DateTime CreateTime, int TicketPriceTypeID, decimal Howmoney, int TicketStateID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.InsectdingpiaoxinxiRequest();
            inValue.FrequencyID = FrequencyID;
            inValue.SeatsID = SeatsID;
            inValue.CreateUserID = CreateUserID;
            inValue.DeleteUserID = DeleteUserID;
            inValue.TicketMark = TicketMark;
            inValue.TicketingDate = TicketingDate;
            inValue.TicketingDateTime = TicketingDateTime;
            inValue.CreateTime = CreateTime;
            inValue.TicketPriceTypeID = TicketPriceTypeID;
            inValue.Howmoney = Howmoney;
            inValue.TicketStateID = TicketStateID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).InsectdingpiaoxinxiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.Selectzuidapiohao(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoRequest request) {
            return base.Channel.Selectzuidapiohao(request);
        }
        
        public System.Data.DataSet Selectzuidapiohao() {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoRequest();
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).Selectzuidapiohao(inValue);
            return retVal.SelectzuidapiohaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.SelectzuidapiohaoAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoRequest request) {
            return base.Channel.SelectzuidapiohaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoResponse> SelectzuidapiohaoAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectzuidapiohaoRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).SelectzuidapiohaoAsync(inValue);
        }
        
        public int DELETETicketingInformation(int TicketingInformationID, int TicketPriceTypeID, int TicketStateID, int Tuipiaoshouxufei) {
            return base.Channel.DELETETicketingInformation(TicketingInformationID, TicketPriceTypeID, TicketStateID, Tuipiaoshouxufei);
        }
        
        public System.Threading.Tasks.Task<int> DELETETicketingInformationAsync(int TicketingInformationID, int TicketPriceTypeID, int TicketStateID, int Tuipiaoshouxufei) {
            return base.Channel.DELETETicketingInformationAsync(TicketingInformationID, TicketPriceTypeID, TicketStateID, Tuipiaoshouxufei);
        }
        
        public int DELETETicketingInformationtuipiao(int TicketingInformationID, int TicketPriceTypeID, int Tuipiaoshouxufei, int TicketStateID) {
            return base.Channel.DELETETicketingInformationtuipiao(TicketingInformationID, TicketPriceTypeID, Tuipiaoshouxufei, TicketStateID);
        }
        
        public System.Threading.Tasks.Task<int> DELETETicketingInformationtuipiaoAsync(int TicketingInformationID, int TicketPriceTypeID, int Tuipiaoshouxufei, int TicketStateID) {
            return base.Channel.DELETETicketingInformationtuipiaoAsync(TicketingInformationID, TicketPriceTypeID, Tuipiaoshouxufei, TicketStateID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.SelectpiaojiaID(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDRequest request) {
            return base.Channel.SelectpiaojiaID(request);
        }
        
        public System.Data.DataSet SelectpiaojiaID(int SeatsID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDRequest();
            inValue.SeatsID = SeatsID;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).SelectpiaojiaID(inValue);
            return retVal.SelectpiaojiaIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.SelectpiaojiaIDAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDRequest request) {
            return base.Channel.SelectpiaojiaIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDResponse> SelectpiaojiaIDAsync(int SeatsID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.SelectpiaojiaIDRequest();
            inValue.SeatsID = SeatsID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).SelectpiaojiaIDAsync(inValue);
        }
        
        public int Updatexiweizhaungtaiweibaofei(int SeatsID, int SeatsStateID) {
            return base.Channel.Updatexiweizhaungtaiweibaofei(SeatsID, SeatsStateID);
        }
        
        public System.Threading.Tasks.Task<int> UpdatexiweizhaungtaiweibaofeiAsync(int SeatsID, int SeatsStateID) {
            return base.Channel.UpdatexiweizhaungtaiweibaofeiAsync(SeatsID, SeatsStateID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.MoHuSelectpiaoxinxi(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiRequest request) {
            return base.Channel.MoHuSelectpiaoxinxi(request);
        }
        
        public System.Data.DataSet MoHuSelectpiaoxinxi(string 动态条件) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiRequest();
            inValue.动态条件 = 动态条件;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).MoHuSelectpiaoxinxi(inValue);
            return retVal.MoHuSelectpiaoxinxiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.MoHuSelectpiaoxinxiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiRequest request) {
            return base.Channel.MoHuSelectpiaoxinxiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiResponse> MoHuSelectpiaoxinxiAsync(string 动态条件) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.MoHuSelectpiaoxinxiRequest();
            inValue.动态条件 = 动态条件;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).MoHuSelectpiaoxinxiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectchexing(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingRequest request) {
            return base.Channel.selectchexing(request);
        }
        
        public System.Data.DataSet selectchexing() {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingRequest();
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectchexing(inValue);
            return retVal.selectchexingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectchexingAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingRequest request) {
            return base.Channel.selectchexingAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingResponse> selectchexingAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectchexingRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectchexingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectpiaoxing(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingRequest request) {
            return base.Channel.selectpiaoxing(request);
        }
        
        public System.Data.DataSet selectpiaoxing() {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingRequest();
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectpiaoxing(inValue);
            return retVal.selectpiaoxingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectpiaoxingAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingRequest request) {
            return base.Channel.selectpiaoxingAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingResponse> selectpiaoxingAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaoxingRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectpiaoxingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectpiaozhaungrtai(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiRequest request) {
            return base.Channel.selectpiaozhaungrtai(request);
        }
        
        public System.Data.DataSet selectpiaozhaungrtai() {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiRequest();
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectpiaozhaungrtai(inValue);
            return retVal.selectpiaozhaungrtaiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectpiaozhaungrtaiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiRequest request) {
            return base.Channel.selectpiaozhaungrtaiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiResponse> selectpiaozhaungrtaiAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectpiaozhaungrtaiRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectpiaozhaungrtaiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectfeipiaoxinxi(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiRequest request) {
            return base.Channel.selectfeipiaoxinxi(request);
        }
        
        public System.Data.DataSet selectfeipiaoxinxi(int SeatsID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiRequest();
            inValue.SeatsID = SeatsID;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectfeipiaoxinxi(inValue);
            return retVal.selectfeipiaoxinxiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectfeipiaoxinxiAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiRequest request) {
            return base.Channel.selectfeipiaoxinxiAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiResponse> selectfeipiaoxinxiAsync(int SeatsID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectfeipiaoxinxiRequest();
            inValue.SeatsID = SeatsID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectfeipiaoxinxiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectgenjuyonghuID(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDRequest request) {
            return base.Channel.selectgenjuyonghuID(request);
        }
        
        public System.Data.DataSet selectgenjuyonghuID(int UserID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDRequest();
            inValue.UserID = UserID;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectgenjuyonghuID(inValue);
            return retVal.selectgenjuyonghuIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectgenjuyonghuIDAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDRequest request) {
            return base.Channel.selectgenjuyonghuIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDResponse> selectgenjuyonghuIDAsync(int UserID) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectgenjuyonghuIDRequest();
            inValue.UserID = UserID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectgenjuyonghuIDAsync(inValue);
        }
        
        public int UPDATEdangqianpiaohao(int CurrentTicketMark, int SurplusQuantity, int ReceiveUserID) {
            return base.Channel.UPDATEdangqianpiaohao(CurrentTicketMark, SurplusQuantity, ReceiveUserID);
        }
        
        public System.Threading.Tasks.Task<int> UPDATEdangqianpiaohaoAsync(int CurrentTicketMark, int SurplusQuantity, int ReceiveUserID) {
            return base.Channel.UPDATEdangqianpiaohaoAsync(CurrentTicketMark, SurplusQuantity, ReceiveUserID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectyanzhengma(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaRequest request) {
            return base.Channel.selectyanzhengma(request);
        }
        
        public System.Data.DataSet selectyanzhengma(string DingPiaoYanZhengMa) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaRequest();
            inValue.DingPiaoYanZhengMa = DingPiaoYanZhengMa;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectyanzhengma(inValue);
            return retVal.selectyanzhengmaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.selectyanzhengmaAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaRequest request) {
            return base.Channel.selectyanzhengmaAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaResponse> selectyanzhengmaAsync(string DingPiaoYanZhengMa) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.selectyanzhengmaRequest();
            inValue.DingPiaoYanZhengMa = DingPiaoYanZhengMa;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).selectyanzhengmaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaResponse 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.updateyanzhengma(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaRequest request) {
            return base.Channel.updateyanzhengma(request);
        }
        
        public int updateyanzhengma(bool ShiFou, string DingPiaoYanZhengMa) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaRequest();
            inValue.ShiFou = ShiFou;
            inValue.DingPiaoYanZhengMa = DingPiaoYanZhengMa;
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).updateyanzhengma(inValue);
            return retVal.updateyanzhengmaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaResponse> 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease.updateyanzhengmaAsync(集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaRequest request) {
            return base.Channel.updateyanzhengmaAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaResponse> updateyanzhengmaAsync(bool ShiFou, string DingPiaoYanZhengMa) {
            集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.updateyanzhengmaRequest();
            inValue.ShiFou = ShiFou;
            inValue.DingPiaoYanZhengMa = DingPiaoYanZhengMa;
            return ((集团客运综合管理系统.BLL集团客运综合管理.SeaseTicket.TicketSease.TicketSease)(this)).updateyanzhengmaAsync(inValue);
        }
    }
}
