//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.UserManager.FRM_YonHuGuanLi_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.UserManager.FRM_YonHuGuanLi_Update.FRM_YonHuGuanLi_Update")]
    public interface FRM_YonHuGuanLi_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectYonHuLeiXing", ReplyAction="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectYonHuLeiXingResponse")]
        System.Data.DataSet SelectYonHuLeiXing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectYonHuLeiXing", ReplyAction="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectYonHuLeiXingResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectYonHuLeiXingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectSuoShuCheZhan", ReplyAction="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectSuoShuCheZhanResponse")]
        System.Data.DataSet SelectSuoShuCheZhan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectSuoShuCheZhan", ReplyAction="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectSuoShuCheZhanResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectSuoShuCheZhanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectYuanGongXinXi", ReplyAction="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectYuanGongXinXiResponse")]
        System.Data.DataSet SelectYuanGongXinXi(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectYuanGongXinXi", ReplyAction="http://tempuri.org/FRM_YonHuGuanLi_Update/SelectYuanGongXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectYuanGongXinXiAsync(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuGuanLi_Update/UpdateYuanGongXinXi", ReplyAction="http://tempuri.org/FRM_YonHuGuanLi_Update/UpdateYuanGongXinXiResponse")]
        int UpdateYuanGongXinXi(int UserTypeID, int CarStandID, string UserCoding, string Password, string Comments, int UserID, string UserMC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_YonHuGuanLi_Update/UpdateYuanGongXinXi", ReplyAction="http://tempuri.org/FRM_YonHuGuanLi_Update/UpdateYuanGongXinXiResponse")]
        System.Threading.Tasks.Task<int> UpdateYuanGongXinXiAsync(int UserTypeID, int CarStandID, string UserCoding, string Password, string Comments, int UserID, string UserMC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_YonHuGuanLi_UpdateChannel : 集团客运综合管理系统.BLL集团客运综合管理.UserManager.FRM_YonHuGuanLi_Update.FRM_YonHuGuanLi_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_YonHuGuanLi_UpdateClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.UserManager.FRM_YonHuGuanLi_Update.FRM_YonHuGuanLi_Update>, 集团客运综合管理系统.BLL集团客运综合管理.UserManager.FRM_YonHuGuanLi_Update.FRM_YonHuGuanLi_Update {
        
        public FRM_YonHuGuanLi_UpdateClient() {
        }
        
        public FRM_YonHuGuanLi_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_YonHuGuanLi_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_YonHuGuanLi_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_YonHuGuanLi_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SelectYonHuLeiXing() {
            return base.Channel.SelectYonHuLeiXing();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectYonHuLeiXingAsync() {
            return base.Channel.SelectYonHuLeiXingAsync();
        }
        
        public System.Data.DataSet SelectSuoShuCheZhan() {
            return base.Channel.SelectSuoShuCheZhan();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectSuoShuCheZhanAsync() {
            return base.Channel.SelectSuoShuCheZhanAsync();
        }
        
        public System.Data.DataSet SelectYuanGongXinXi(int UserID) {
            return base.Channel.SelectYuanGongXinXi(UserID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectYuanGongXinXiAsync(int UserID) {
            return base.Channel.SelectYuanGongXinXiAsync(UserID);
        }
        
        public int UpdateYuanGongXinXi(int UserTypeID, int CarStandID, string UserCoding, string Password, string Comments, int UserID, string UserMC) {
            return base.Channel.UpdateYuanGongXinXi(UserTypeID, CarStandID, UserCoding, Password, Comments, UserID, UserMC);
        }
        
        public System.Threading.Tasks.Task<int> UpdateYuanGongXinXiAsync(int UserTypeID, int CarStandID, string UserCoding, string Password, string Comments, int UserID, string UserMC) {
            return base.Channel.UpdateYuanGongXinXiAsync(UserTypeID, CarStandID, UserCoding, Password, Comments, UserID, UserMC);
        }
    }
}
