//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli")]
    public interface Campseizedmoneyguanli {
        
        // CODEGEN: 参数“selectyonghuResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Campseizedmoneyguanli/selectyonghu", ReplyAction="http://tempuri.org/Campseizedmoneyguanli/selectyonghuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuResponse selectyonghu(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Campseizedmoneyguanli/selectyonghu", ReplyAction="http://tempuri.org/Campseizedmoneyguanli/selectyonghuResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuResponse> selectyonghuAsync(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuRequest request);
        
        // CODEGEN: 参数“Campseizedmoney_selectdangqianpiaohaoResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_selectdangqianpiaohao", ReplyAction="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_selectdangqianpiaohaoRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoResponse Campseizedmoney_selectdangqianpiaohao(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_selectdangqianpiaohao", ReplyAction="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_selectdangqianpiaohaoRes" +
            "ponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoResponse> Campseizedmoney_selectdangqianpiaohaoAsync(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoRequest request);
        
        // CODEGEN: 参数“Campseizedmoney_selectshoupiaozhangshuResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_selectshoupiaozhangshu", ReplyAction="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_selectshoupiaozhangshuRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuResponse Campseizedmoney_selectshoupiaozhangshu(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_selectshoupiaozhangshu", ReplyAction="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_selectshoupiaozhangshuRe" +
            "sponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuResponse> Campseizedmoney_selectshoupiaozhangshuAsync(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuRequest request);
        
        // CODEGEN: 参数“UserCoding”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_insectyingshoujiaofeidan" +
            "", ReplyAction="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_insectyingshoujiaofeidan" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanResponse Campseizedmoney_insectyingshoujiaofeidan(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_insectyingshoujiaofeidan" +
            "", ReplyAction="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_insectyingshoujiaofeidan" +
            "Response")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanResponse> Campseizedmoney_insectyingshoujiaofeidanAsync(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanRequest request);
        
        // CODEGEN: 参数“Campseizedmoney_yingshoudanResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_yingshoudan", ReplyAction="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_yingshoudanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanResponse Campseizedmoney_yingshoudan(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_yingshoudan", ReplyAction="http://tempuri.org/Campseizedmoneyguanli/Campseizedmoney_yingshoudanResponse")]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanResponse> Campseizedmoney_yingshoudanAsync(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectyonghu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectyonghuRequest {
        
        public selectyonghuRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectyonghuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class selectyonghuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet selectyonghuResult;
        
        public selectyonghuResponse() {
        }
        
        public selectyonghuResponse(System.Data.DataSet selectyonghuResult) {
            this.selectyonghuResult = selectyonghuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Campseizedmoney_selectdangqianpiaohao", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Campseizedmoney_selectdangqianpiaohaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserID;
        
        public Campseizedmoney_selectdangqianpiaohaoRequest() {
        }
        
        public Campseizedmoney_selectdangqianpiaohaoRequest(int UserID) {
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Campseizedmoney_selectdangqianpiaohaoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Campseizedmoney_selectdangqianpiaohaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet Campseizedmoney_selectdangqianpiaohaoResult;
        
        public Campseizedmoney_selectdangqianpiaohaoResponse() {
        }
        
        public Campseizedmoney_selectdangqianpiaohaoResponse(System.Data.DataSet Campseizedmoney_selectdangqianpiaohaoResult) {
            this.Campseizedmoney_selectdangqianpiaohaoResult = Campseizedmoney_selectdangqianpiaohaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Campseizedmoney_selectshoupiaozhangshu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Campseizedmoney_selectshoupiaozhangshuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime TicketingDate;
        
        public Campseizedmoney_selectshoupiaozhangshuRequest() {
        }
        
        public Campseizedmoney_selectshoupiaozhangshuRequest(int UserID, System.DateTime TicketingDate) {
            this.UserID = UserID;
            this.TicketingDate = TicketingDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Campseizedmoney_selectshoupiaozhangshuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Campseizedmoney_selectshoupiaozhangshuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet Campseizedmoney_selectshoupiaozhangshuResult;
        
        public Campseizedmoney_selectshoupiaozhangshuResponse() {
        }
        
        public Campseizedmoney_selectshoupiaozhangshuResponse(System.Data.DataSet Campseizedmoney_selectshoupiaozhangshuResult) {
            this.Campseizedmoney_selectshoupiaozhangshuResult = Campseizedmoney_selectshoupiaozhangshuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Campseizedmoney_insectyingshoujiaofeidan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Campseizedmoney_insectyingshoujiaofeidanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserCoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int Shoupiaozhangshu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public decimal Shoupiaojine;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int tuipiaozhangshu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public decimal tuipiaojine;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int feipiaozhangshu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public decimal feipiaojine;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public decimal jiankuanjine;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public System.DateTime Createtime;
        
        public Campseizedmoney_insectyingshoujiaofeidanRequest() {
        }
        
        public Campseizedmoney_insectyingshoujiaofeidanRequest(string UserCoding, int UserID, int Shoupiaozhangshu, decimal Shoupiaojine, int tuipiaozhangshu, decimal tuipiaojine, int feipiaozhangshu, decimal feipiaojine, decimal jiankuanjine, string Comments, System.DateTime Createtime) {
            this.UserCoding = UserCoding;
            this.UserID = UserID;
            this.Shoupiaozhangshu = Shoupiaozhangshu;
            this.Shoupiaojine = Shoupiaojine;
            this.tuipiaozhangshu = tuipiaozhangshu;
            this.tuipiaojine = tuipiaojine;
            this.feipiaozhangshu = feipiaozhangshu;
            this.feipiaojine = feipiaojine;
            this.jiankuanjine = jiankuanjine;
            this.Comments = Comments;
            this.Createtime = Createtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Campseizedmoney_insectyingshoujiaofeidanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Campseizedmoney_insectyingshoujiaofeidanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Campseizedmoney_insectyingshoujiaofeidanResult;
        
        public Campseizedmoney_insectyingshoujiaofeidanResponse() {
        }
        
        public Campseizedmoney_insectyingshoujiaofeidanResponse(int Campseizedmoney_insectyingshoujiaofeidanResult) {
            this.Campseizedmoney_insectyingshoujiaofeidanResult = Campseizedmoney_insectyingshoujiaofeidanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Campseizedmoney_yingshoudan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Campseizedmoney_yingshoudanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserID;
        
        public Campseizedmoney_yingshoudanRequest() {
        }
        
        public Campseizedmoney_yingshoudanRequest(int UserID) {
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Campseizedmoney_yingshoudanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Campseizedmoney_yingshoudanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet Campseizedmoney_yingshoudanResult;
        
        public Campseizedmoney_yingshoudanResponse() {
        }
        
        public Campseizedmoney_yingshoudanResponse(System.Data.DataSet Campseizedmoney_yingshoudanResult) {
            this.Campseizedmoney_yingshoudanResult = Campseizedmoney_yingshoudanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CampseizedmoneyguanliChannel : 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CampseizedmoneyguanliClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli>, 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli {
        
        public CampseizedmoneyguanliClient() {
        }
        
        public CampseizedmoneyguanliClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampseizedmoneyguanliClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampseizedmoneyguanliClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampseizedmoneyguanliClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuResponse 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli.selectyonghu(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuRequest request) {
            return base.Channel.selectyonghu(request);
        }
        
        public System.Data.DataSet selectyonghu() {
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuRequest();
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli)(this)).selectyonghu(inValue);
            return retVal.selectyonghuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuResponse> 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli.selectyonghuAsync(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuRequest request) {
            return base.Channel.selectyonghuAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuResponse> selectyonghuAsync() {
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.selectyonghuRequest();
            return ((集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli)(this)).selectyonghuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoResponse 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohao(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoRequest request) {
            return base.Channel.Campseizedmoney_selectdangqianpiaohao(request);
        }
        
        public System.Data.DataSet Campseizedmoney_selectdangqianpiaohao(int UserID) {
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoRequest();
            inValue.UserID = UserID;
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli)(this)).Campseizedmoney_selectdangqianpiaohao(inValue);
            return retVal.Campseizedmoney_selectdangqianpiaohaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoResponse> 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoAsync(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoRequest request) {
            return base.Channel.Campseizedmoney_selectdangqianpiaohaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoResponse> Campseizedmoney_selectdangqianpiaohaoAsync(int UserID) {
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectdangqianpiaohaoRequest();
            inValue.UserID = UserID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli)(this)).Campseizedmoney_selectdangqianpiaohaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuResponse 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshu(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuRequest request) {
            return base.Channel.Campseizedmoney_selectshoupiaozhangshu(request);
        }
        
        public System.Data.DataSet Campseizedmoney_selectshoupiaozhangshu(int UserID, System.DateTime TicketingDate) {
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuRequest();
            inValue.UserID = UserID;
            inValue.TicketingDate = TicketingDate;
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli)(this)).Campseizedmoney_selectshoupiaozhangshu(inValue);
            return retVal.Campseizedmoney_selectshoupiaozhangshuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuResponse> 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuAsync(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuRequest request) {
            return base.Channel.Campseizedmoney_selectshoupiaozhangshuAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuResponse> Campseizedmoney_selectshoupiaozhangshuAsync(int UserID, System.DateTime TicketingDate) {
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_selectshoupiaozhangshuRequest();
            inValue.UserID = UserID;
            inValue.TicketingDate = TicketingDate;
            return ((集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli)(this)).Campseizedmoney_selectshoupiaozhangshuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanResponse 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidan(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanRequest request) {
            return base.Channel.Campseizedmoney_insectyingshoujiaofeidan(request);
        }
        
        public int Campseizedmoney_insectyingshoujiaofeidan(string UserCoding, int UserID, int Shoupiaozhangshu, decimal Shoupiaojine, int tuipiaozhangshu, decimal tuipiaojine, int feipiaozhangshu, decimal feipiaojine, decimal jiankuanjine, string Comments, System.DateTime Createtime) {
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanRequest();
            inValue.UserCoding = UserCoding;
            inValue.UserID = UserID;
            inValue.Shoupiaozhangshu = Shoupiaozhangshu;
            inValue.Shoupiaojine = Shoupiaojine;
            inValue.tuipiaozhangshu = tuipiaozhangshu;
            inValue.tuipiaojine = tuipiaojine;
            inValue.feipiaozhangshu = feipiaozhangshu;
            inValue.feipiaojine = feipiaojine;
            inValue.jiankuanjine = jiankuanjine;
            inValue.Comments = Comments;
            inValue.Createtime = Createtime;
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli)(this)).Campseizedmoney_insectyingshoujiaofeidan(inValue);
            return retVal.Campseizedmoney_insectyingshoujiaofeidanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanResponse> 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanAsync(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanRequest request) {
            return base.Channel.Campseizedmoney_insectyingshoujiaofeidanAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanResponse> Campseizedmoney_insectyingshoujiaofeidanAsync(string UserCoding, int UserID, int Shoupiaozhangshu, decimal Shoupiaojine, int tuipiaozhangshu, decimal tuipiaojine, int feipiaozhangshu, decimal feipiaojine, decimal jiankuanjine, string Comments, System.DateTime Createtime) {
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_insectyingshoujiaofeidanRequest();
            inValue.UserCoding = UserCoding;
            inValue.UserID = UserID;
            inValue.Shoupiaozhangshu = Shoupiaozhangshu;
            inValue.Shoupiaojine = Shoupiaojine;
            inValue.tuipiaozhangshu = tuipiaozhangshu;
            inValue.tuipiaojine = tuipiaojine;
            inValue.feipiaozhangshu = feipiaozhangshu;
            inValue.feipiaojine = feipiaojine;
            inValue.jiankuanjine = jiankuanjine;
            inValue.Comments = Comments;
            inValue.Createtime = Createtime;
            return ((集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli)(this)).Campseizedmoney_insectyingshoujiaofeidanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanResponse 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli.Campseizedmoney_yingshoudan(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanRequest request) {
            return base.Channel.Campseizedmoney_yingshoudan(request);
        }
        
        public System.Data.DataSet Campseizedmoney_yingshoudan(int UserID) {
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanRequest();
            inValue.UserID = UserID;
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanResponse retVal = ((集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli)(this)).Campseizedmoney_yingshoudan(inValue);
            return retVal.Campseizedmoney_yingshoudanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanResponse> 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli.Campseizedmoney_yingshoudanAsync(集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanRequest request) {
            return base.Channel.Campseizedmoney_yingshoudanAsync(request);
        }
        
        public System.Threading.Tasks.Task<集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanResponse> Campseizedmoney_yingshoudanAsync(int UserID) {
            集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanRequest inValue = new 集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoney_yingshoudanRequest();
            inValue.UserID = UserID;
            return ((集团客运综合管理系统.BLL集团客运综合管理.CampseizedmoneyManager.Campseizedmoneyguanli.Campseizedmoneyguanli)(this)).Campseizedmoney_yingshoudanAsync(inValue);
        }
    }
}
