//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_CheLiangGuangLi_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.VehicleManage.FRM_CheLiangGuangLi_Update.FRM_CheLiangGuangLi_Update")]
    public interface FRM_CheLiangGuangLi_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectDriverNumber", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectDriverNumberResponse")]
        System.Data.DataSet SelectDriverNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectDriverNumber", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectDriverNumberResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectDriverNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectJiaShiYuanByDriverNumber", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectJiaShiYuanByDriverNumberRespo" +
            "nse")]
        System.Data.DataSet SelectJiaShiYuanByDriverNumber(string DriverNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectJiaShiYuanByDriverNumber", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectJiaShiYuanByDriverNumberRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectJiaShiYuanByDriverNumberAsync(string DriverNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectChengBaoGonSi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectChengBaoGonSiResponse")]
        System.Data.DataSet SelectChengBaoGonSi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectChengBaoGonSi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectChengBaoGonSiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectChengBaoGonSiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheShuDangWei", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheShuDangWeiResponse")]
        System.Data.DataSet SelectCheShuDangWei();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheShuDangWei", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheShuDangWeiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheShuDangWeiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheLiangLeiXing", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheLiangLeiXingResponse")]
        System.Data.DataSet SelectCheLiangLeiXing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheLiangLeiXing", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheLiangLeiXingResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangLeiXingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheLiangXinXiByVehicleID", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheLiangXinXiByVehicleIDRespo" +
            "nse")]
        System.Data.DataSet SelectCheLiangXinXiByVehicleID(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheLiangXinXiByVehicleID", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/SelectCheLiangXinXiByVehicleIDRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangXinXiByVehicleIDAsync(int VehicleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateCheLiangXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateCheLiangXinXiResponse")]
        int UpdateCheLiangXinXi(int VehicleTypeID, int CarBelongToTheUnitID, int DriverID, int DriverAssistantID, string VehiclePaiNumber, string VehicleNumber, System.DateTime RegisterDate, bool SafeInspectNo, bool EverySkySafeInspect, bool OneSkySafeInspectOneNext, string Comment, int VehicleID, string Loadheaver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateCheLiangXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateCheLiangXinXiResponse")]
        System.Threading.Tasks.Task<int> UpdateCheLiangXinXiAsync(int VehicleTypeID, int CarBelongToTheUnitID, int DriverID, int DriverAssistantID, string VehiclePaiNumber, string VehicleNumber, System.DateTime RegisterDate, bool SafeInspectNo, bool EverySkySafeInspect, bool OneSkySafeInspectOneNext, string Comment, int VehicleID, string Loadheaver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateCheZhuXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateCheZhuXinXiResponse")]
        int UpdateCheZhuXinXi(string VehicleHostMC, string Address, string ContactPhone, string Identification, int VehicleHostID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateCheZhuXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateCheZhuXinXiResponse")]
        System.Threading.Tasks.Task<int> UpdateCheZhuXinXiAsync(string VehicleHostMC, string Address, string ContactPhone, string Identification, int VehicleHostID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateBaoXianXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateBaoXianXinXiResponse")]
        int UpdateBaoXianXinXi(int UnderwriteCompanyID, string PolicyOfInsuranceMC, System.DateTime BookbuildingDate, System.DateTime Drivenvehicle, System.DateTime CommercialUnderwritingExecutive, System.DateTime Bearingonetransportrisk, int PolicyOfInsuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateBaoXianXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateBaoXianXinXiResponse")]
        System.Threading.Tasks.Task<int> UpdateBaoXianXinXiAsync(int UnderwriteCompanyID, string PolicyOfInsuranceMC, System.DateTime BookbuildingDate, System.DateTime Drivenvehicle, System.DateTime CommercialUnderwritingExecutive, System.DateTime Bearingonetransportrisk, int PolicyOfInsuranceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateZhengJianXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateZhengJianXinXiResponse")]
        int UpdateZhengJianXinXi(string BusinessLine, string LineNumber, string AttachedCardNumber, string OperationOfTheNumber, System.DateTime Validity, System.DateTime SpringRecords, System.DateTime InspectionRecords, System.DateTime CompleteMaintenance, System.DateTime Rating, System.DateTime TravelCard, System.DateTime MonthMaintainSun, System.DateTime LiquefiedPetroleumGasCard, int VehicleLicenseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateZhengJianXinXi", ReplyAction="http://tempuri.org/FRM_CheLiangGuangLi_Update/UpdateZhengJianXinXiResponse")]
        System.Threading.Tasks.Task<int> UpdateZhengJianXinXiAsync(string BusinessLine, string LineNumber, string AttachedCardNumber, string OperationOfTheNumber, System.DateTime Validity, System.DateTime SpringRecords, System.DateTime InspectionRecords, System.DateTime CompleteMaintenance, System.DateTime Rating, System.DateTime TravelCard, System.DateTime MonthMaintainSun, System.DateTime LiquefiedPetroleumGasCard, int VehicleLicenseID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_CheLiangGuangLi_UpdateChannel : 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_CheLiangGuangLi_Update.FRM_CheLiangGuangLi_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_CheLiangGuangLi_UpdateClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_CheLiangGuangLi_Update.FRM_CheLiangGuangLi_Update>, 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_CheLiangGuangLi_Update.FRM_CheLiangGuangLi_Update {
        
        public FRM_CheLiangGuangLi_UpdateClient() {
        }
        
        public FRM_CheLiangGuangLi_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_CheLiangGuangLi_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_CheLiangGuangLi_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_CheLiangGuangLi_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SelectDriverNumber() {
            return base.Channel.SelectDriverNumber();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectDriverNumberAsync() {
            return base.Channel.SelectDriverNumberAsync();
        }
        
        public System.Data.DataSet SelectJiaShiYuanByDriverNumber(string DriverNumber) {
            return base.Channel.SelectJiaShiYuanByDriverNumber(DriverNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectJiaShiYuanByDriverNumberAsync(string DriverNumber) {
            return base.Channel.SelectJiaShiYuanByDriverNumberAsync(DriverNumber);
        }
        
        public System.Data.DataSet SelectChengBaoGonSi() {
            return base.Channel.SelectChengBaoGonSi();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectChengBaoGonSiAsync() {
            return base.Channel.SelectChengBaoGonSiAsync();
        }
        
        public System.Data.DataSet SelectCheShuDangWei() {
            return base.Channel.SelectCheShuDangWei();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheShuDangWeiAsync() {
            return base.Channel.SelectCheShuDangWeiAsync();
        }
        
        public System.Data.DataSet SelectCheLiangLeiXing() {
            return base.Channel.SelectCheLiangLeiXing();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangLeiXingAsync() {
            return base.Channel.SelectCheLiangLeiXingAsync();
        }
        
        public System.Data.DataSet SelectCheLiangXinXiByVehicleID(int VehicleID) {
            return base.Channel.SelectCheLiangXinXiByVehicleID(VehicleID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectCheLiangXinXiByVehicleIDAsync(int VehicleID) {
            return base.Channel.SelectCheLiangXinXiByVehicleIDAsync(VehicleID);
        }
        
        public int UpdateCheLiangXinXi(int VehicleTypeID, int CarBelongToTheUnitID, int DriverID, int DriverAssistantID, string VehiclePaiNumber, string VehicleNumber, System.DateTime RegisterDate, bool SafeInspectNo, bool EverySkySafeInspect, bool OneSkySafeInspectOneNext, string Comment, int VehicleID, string Loadheaver) {
            return base.Channel.UpdateCheLiangXinXi(VehicleTypeID, CarBelongToTheUnitID, DriverID, DriverAssistantID, VehiclePaiNumber, VehicleNumber, RegisterDate, SafeInspectNo, EverySkySafeInspect, OneSkySafeInspectOneNext, Comment, VehicleID, Loadheaver);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCheLiangXinXiAsync(int VehicleTypeID, int CarBelongToTheUnitID, int DriverID, int DriverAssistantID, string VehiclePaiNumber, string VehicleNumber, System.DateTime RegisterDate, bool SafeInspectNo, bool EverySkySafeInspect, bool OneSkySafeInspectOneNext, string Comment, int VehicleID, string Loadheaver) {
            return base.Channel.UpdateCheLiangXinXiAsync(VehicleTypeID, CarBelongToTheUnitID, DriverID, DriverAssistantID, VehiclePaiNumber, VehicleNumber, RegisterDate, SafeInspectNo, EverySkySafeInspect, OneSkySafeInspectOneNext, Comment, VehicleID, Loadheaver);
        }
        
        public int UpdateCheZhuXinXi(string VehicleHostMC, string Address, string ContactPhone, string Identification, int VehicleHostID) {
            return base.Channel.UpdateCheZhuXinXi(VehicleHostMC, Address, ContactPhone, Identification, VehicleHostID);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCheZhuXinXiAsync(string VehicleHostMC, string Address, string ContactPhone, string Identification, int VehicleHostID) {
            return base.Channel.UpdateCheZhuXinXiAsync(VehicleHostMC, Address, ContactPhone, Identification, VehicleHostID);
        }
        
        public int UpdateBaoXianXinXi(int UnderwriteCompanyID, string PolicyOfInsuranceMC, System.DateTime BookbuildingDate, System.DateTime Drivenvehicle, System.DateTime CommercialUnderwritingExecutive, System.DateTime Bearingonetransportrisk, int PolicyOfInsuranceID) {
            return base.Channel.UpdateBaoXianXinXi(UnderwriteCompanyID, PolicyOfInsuranceMC, BookbuildingDate, Drivenvehicle, CommercialUnderwritingExecutive, Bearingonetransportrisk, PolicyOfInsuranceID);
        }
        
        public System.Threading.Tasks.Task<int> UpdateBaoXianXinXiAsync(int UnderwriteCompanyID, string PolicyOfInsuranceMC, System.DateTime BookbuildingDate, System.DateTime Drivenvehicle, System.DateTime CommercialUnderwritingExecutive, System.DateTime Bearingonetransportrisk, int PolicyOfInsuranceID) {
            return base.Channel.UpdateBaoXianXinXiAsync(UnderwriteCompanyID, PolicyOfInsuranceMC, BookbuildingDate, Drivenvehicle, CommercialUnderwritingExecutive, Bearingonetransportrisk, PolicyOfInsuranceID);
        }
        
        public int UpdateZhengJianXinXi(string BusinessLine, string LineNumber, string AttachedCardNumber, string OperationOfTheNumber, System.DateTime Validity, System.DateTime SpringRecords, System.DateTime InspectionRecords, System.DateTime CompleteMaintenance, System.DateTime Rating, System.DateTime TravelCard, System.DateTime MonthMaintainSun, System.DateTime LiquefiedPetroleumGasCard, int VehicleLicenseID) {
            return base.Channel.UpdateZhengJianXinXi(BusinessLine, LineNumber, AttachedCardNumber, OperationOfTheNumber, Validity, SpringRecords, InspectionRecords, CompleteMaintenance, Rating, TravelCard, MonthMaintainSun, LiquefiedPetroleumGasCard, VehicleLicenseID);
        }
        
        public System.Threading.Tasks.Task<int> UpdateZhengJianXinXiAsync(string BusinessLine, string LineNumber, string AttachedCardNumber, string OperationOfTheNumber, System.DateTime Validity, System.DateTime SpringRecords, System.DateTime InspectionRecords, System.DateTime CompleteMaintenance, System.DateTime Rating, System.DateTime TravelCard, System.DateTime MonthMaintainSun, System.DateTime LiquefiedPetroleumGasCard, int VehicleLicenseID) {
            return base.Channel.UpdateZhengJianXinXiAsync(BusinessLine, LineNumber, AttachedCardNumber, OperationOfTheNumber, Validity, SpringRecords, InspectionRecords, CompleteMaintenance, Rating, TravelCard, MonthMaintainSun, LiquefiedPetroleumGasCard, VehicleLicenseID);
        }
    }
}
