//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_JiaShiYuanXinXi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.VehicleManage.FRM_JiaShiYuanXinXi.FRM_JiaShiYuanXinXi")]
    public interface FRM_JiaShiYuanXinXi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JiaShiYuanXinXi/SelectJiaShiYuanXinXi", ReplyAction="http://tempuri.org/FRM_JiaShiYuanXinXi/SelectJiaShiYuanXinXiResponse")]
        System.Data.DataSet SelectJiaShiYuanXinXi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JiaShiYuanXinXi/SelectJiaShiYuanXinXi", ReplyAction="http://tempuri.org/FRM_JiaShiYuanXinXi/SelectJiaShiYuanXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectJiaShiYuanXinXiAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_JiaShiYuanXinXiChannel : 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_JiaShiYuanXinXi.FRM_JiaShiYuanXinXi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_JiaShiYuanXinXiClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_JiaShiYuanXinXi.FRM_JiaShiYuanXinXi>, 集团客运综合管理系统.BLL集团客运综合管理.VehicleManage.FRM_JiaShiYuanXinXi.FRM_JiaShiYuanXinXi {
        
        public FRM_JiaShiYuanXinXiClient() {
        }
        
        public FRM_JiaShiYuanXinXiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_JiaShiYuanXinXiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JiaShiYuanXinXiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JiaShiYuanXinXiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SelectJiaShiYuanXinXi() {
            return base.Channel.SelectJiaShiYuanXinXi();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectJiaShiYuanXinXiAsync() {
            return base.Channel.SelectJiaShiYuanXinXiAsync();
        }
    }
}
