//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuChuKu_Update {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuChuKu_Update.FRM_PiaoJuChuKu_Update" +
        "")]
    public interface FRM_PiaoJuChuKu_Update {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectYuanGon", ReplyAction="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectYuanGonResponse")]
        System.Data.DataSet SelectYuanGon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectYuanGon", ReplyAction="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectYuanGonResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectYuanGonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectShiYongZhuangTai", ReplyAction="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectShiYongZhuangTaiResponse")]
        System.Data.DataSet SelectShiYongZhuangTai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectShiYongZhuangTai", ReplyAction="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectShiYongZhuangTaiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectShiYongZhuangTaiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectPiaoJuChuKu", ReplyAction="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectPiaoJuChuKuResponse")]
        System.Data.DataSet SelectPiaoJuChuKu(int BillremovalD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectPiaoJuChuKu", ReplyAction="http://tempuri.org/FRM_PiaoJuChuKu_Update/SelectPiaoJuChuKuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectPiaoJuChuKuAsync(int BillremovalD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuChuKu_Update/UpdatePiaoJuChuKuXinXi", ReplyAction="http://tempuri.org/FRM_PiaoJuChuKu_Update/UpdatePiaoJuChuKuXinXiResponse")]
        int UpdatePiaoJuChuKuXinXi(int UseStateID, int ReceiveUserID, string Comment, int BillremovalD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PiaoJuChuKu_Update/UpdatePiaoJuChuKuXinXi", ReplyAction="http://tempuri.org/FRM_PiaoJuChuKu_Update/UpdatePiaoJuChuKuXinXiResponse")]
        System.Threading.Tasks.Task<int> UpdatePiaoJuChuKuXinXiAsync(int UseStateID, int ReceiveUserID, string Comment, int BillremovalD);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_PiaoJuChuKu_UpdateChannel : 集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuChuKu_Update.FRM_PiaoJuChuKu_Update, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_PiaoJuChuKu_UpdateClient : System.ServiceModel.ClientBase<集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuChuKu_Update.FRM_PiaoJuChuKu_Update>, 集团客运综合管理系统.BLL集团客运综合管理.BiIIEnterlibraryManager.FRM_PiaoJuChuKu_Update.FRM_PiaoJuChuKu_Update {
        
        public FRM_PiaoJuChuKu_UpdateClient() {
        }
        
        public FRM_PiaoJuChuKu_UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_PiaoJuChuKu_UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PiaoJuChuKu_UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PiaoJuChuKu_UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SelectYuanGon() {
            return base.Channel.SelectYuanGon();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectYuanGonAsync() {
            return base.Channel.SelectYuanGonAsync();
        }
        
        public System.Data.DataSet SelectShiYongZhuangTai() {
            return base.Channel.SelectShiYongZhuangTai();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectShiYongZhuangTaiAsync() {
            return base.Channel.SelectShiYongZhuangTaiAsync();
        }
        
        public System.Data.DataSet SelectPiaoJuChuKu(int BillremovalD) {
            return base.Channel.SelectPiaoJuChuKu(BillremovalD);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectPiaoJuChuKuAsync(int BillremovalD) {
            return base.Channel.SelectPiaoJuChuKuAsync(BillremovalD);
        }
        
        public int UpdatePiaoJuChuKuXinXi(int UseStateID, int ReceiveUserID, string Comment, int BillremovalD) {
            return base.Channel.UpdatePiaoJuChuKuXinXi(UseStateID, ReceiveUserID, Comment, BillremovalD);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePiaoJuChuKuXinXiAsync(int UseStateID, int ReceiveUserID, string Comment, int BillremovalD) {
            return base.Channel.UpdatePiaoJuChuKuXinXiAsync(UseStateID, ReceiveUserID, Comment, BillremovalD);
        }
    }
}
